apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubearmor-operator
spec:
  selector:
    matchLabels:
      kubearmor-app: kubearmor-operator
  template:
    metadata:
      annotations:
        container.apparmor.security.beta.kubernetes.io/manager: unconfined
        kubectl.kubernetes.io/default-container: operator
      labels:
        kubearmor-app: kubearmor-operator
    spec:
      securityContext:
        runAsNonRoot: true
      serviceAccountName: kubearmor-operator
      containers:
      - name: operator
        image: kubearmor/kubearmor-operator:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: KUBEARMOR_OPERATOR_NS
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        args:
          - --leader-elect
          - --health-probe-bind-address=:8081
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10