Vagrant.require_version ">= 2.0.0"

if ENV['NETNEXT'] == "1" then
	# Using Cilium's Ubuntu Next image https://app.vagrantup.com/cilium/boxes/ubuntu-next
	VM_IMG = "cilium/ubuntu-next"
	VM_NAME = "kubearmor-dev-next"
else
	VM_IMG = "ubuntu/bionic64"
	VM_NAME = "kubearmor-dev"
end

Vagrant.configure("2") do |config|
  config.vm.define "KubeArmor-Dev" do |cfg|
    cfg.vm.box = VM_IMG
    cfg.vm.provider "virtualbox" do |vb|
      vb.name = VM_NAME
      vb.memory = "4096"
      vb.cpus = 4
      vb.customize ['modifyvm', :id, '--nested-hw-virt', 'on']
    end
  end

  # vagrant@VM_NAME
  config.vm.hostname = VM_NAME

  # sync directories
  kubearmor_home = "../.."
  config.vm.synced_folder kubearmor_home, "/home/vagrant/KubeArmor"

  # copy ssh keys
  config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "/home/vagrant/.ssh/id_rsa.pub"
  config.vm.provision :shell, :inline => "cat /home/vagrant/.ssh/id_rsa.pub >> /home/vagrant/.ssh/authorized_keys", run: "always"

  # copy git config
  config.vm.provision :file, source: "~/.gitconfig", destination: "$HOME/.gitconfig"

  # Provision bash scripts
  config.vm.provision :shell, path: kubearmor_home + "/contribution/self-managed-k8s/setup.sh"
  config.vm.provision :shell, path: kubearmor_home + "/contribution/self-managed-k8s/docker/install_docker.sh"
  config.vm.provision :shell, path: kubearmor_home + "/contribution/self-managed-k8s/k8s/install_kubernetes.sh"

  # Provision inline
  config.vm.provision :shell, inline: "chown -R vagrant:vagrant /home/vagrant/go"

  # Initialize Kubernetes
  config.vm.provision :shell, path: kubearmor_home + "/contribution/self-managed-k8s/k8s/initialize_kubernetes.sh"
end
