# permissions for end users to view kubearmorpolicies and kubearmorclusterpolicies
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubearmorpolicy-viewer-role
rules:
- apiGroups:
  - security.kubearmor.com
  resources:
  - kubearmorpolicies
  - kubearmorclusterpolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - security.kubearmor.com
  resources:
  - kubearmorpolicies/status
  - kubearmorclusterpolicies/status
  verbs:
  - get
