header:
  license:
    spdx-id: Apache-2.0
    copyright-owner: KubeArmor
    content: |
      SPDX-License-Identifier: Apache-2.0
      Copyright 2021 Authors of KubeArmor

  paths:
    - "**/*.go"
    - "**/*.sh"
    - "**/Dockerfile"
    - "**/Makefile"

  paths-ignore:
    - "KubeArmor/BPF/*"
    - "protobuf/*"

  comment: on-failure

dependency:
  files:
    - go.mod
