// SPDX-License-Identifier: Apache-2.0
// Copyright 2022 Authors of KubeArmor

// Code generated by client-gen. DO NOT EDIT.

package v1

type KubeArmorHostPolicyExpansion interface{}

type KubeArmorPolicyExpansion interface{}
