apiVersion: v1
kind: Namespace
metadata:
  name: multiubuntu
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-1-deployment
  namespace: multiubuntu
  labels:
    deployment: ubuntu-1
spec:
  replicas: 1
  selector:
    matchLabels:
      group: group-1
      container: ubuntu-1
  template:
    metadata:
      labels:
        group: group-1
        container: ubuntu-1
      # annotations:
      #   kubearmor-policy: enabled
      #   kubearmor-visibility: process,file,network
    spec:
      containers:
        - name: ubuntu-1-container
          image: kubearmor/ubuntu-w-utils:0.1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-2-deployment
  namespace: multiubuntu
  labels:
    deployment: ubuntu-2
spec:
  replicas: 1
  selector:
    matchLabels:
      group: group-1
      container: ubuntu-2
  template:
    metadata:
      labels:
        group: group-1
        container: ubuntu-2
      # annotations:
      #   kubearmor-policy: enabled
      #   kubearmor-visibility: process,file,network
    spec:
      containers:
        - name: ubuntu-2-container
          image: kubearmor/ubuntu-w-utils:0.1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-3-deployment
  namespace: multiubuntu
  labels:
    deployment: ubuntu-3
spec:
  replicas: 1
  selector:
    matchLabels:
      group: group-1
      container: ubuntu-3
  template:
    metadata:
      labels:
        group: group-1
        container: ubuntu-3
      # annotations:
      #   kubearmor-policy: enabled
      #   kubearmor-visibility: process,file,network
    spec:
      containers:
        - name: ubuntu-3-container
          image: kubearmor/ubuntu-w-utils:0.1
          volumeMounts:
            - name: var-log-path
              mountPath: /host/var/log
      volumes:
        - name: var-log-path
          hostPath:
            path: /var/log
            type: Directory
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-4-deployment
  namespace: multiubuntu
  labels:
    deployment: ubuntu-4
spec:
  replicas: 1
  selector:
    matchLabels:
      group: group-2
      container: ubuntu-4
  template:
    metadata:
      labels:
        group: group-2
        container: ubuntu-4
      # annotations:
      #   kubearmor-policy: enabled
      #   kubearmor-visibility: process,file,network
    spec:
      containers:
        - name: ubuntu-4-container
          image: kubearmor/ubuntu-w-utils:0.1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-5-deployment
  namespace: multiubuntu
  labels:
    deployment: ubuntu-5
spec:
  replicas: 1
  selector:
    matchLabels:
      group: group-2
      container: ubuntu-5
  template:
    metadata:
      labels:
        group: group-2
        container: ubuntu-5
      # annotations:
      #   kubearmor-policy: enabled
      #   kubearmor-visibility: process,file,network
    spec:
      containers:
        - name: ubuntu-5-container
          image: kubearmor/ubuntu-w-utils:0.1
