# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Authors of KubeArmor
#
# Configuration for macOS newsyslog log file rotation
# Location: /etc/newsyslog.d/io.kubearmor.conf
#
# Format:
# logfilename                         [owner:group]  mode count size(KB) when  flags [/pid_file] [sig_num]
/var/log/kubearmor/kubearmor.log      root:wheel     644  5     10240    *     J
/var/log/kubearmor/kubearmor.out.log  root:wheel     644  5     10240    *     J
/var/log/kubearmor/kubearmor.err.log  root:wheel     644  5     10240    *     J
