// SPDX-License-Identifier: Apache-2.0
// Copyright 2021 Authors of KubeArmor

// Code generated by lister-gen. DO NOT EDIT.

package v1

// KubeArmorHostPolicyListerExpansion allows custom methods to be added to
// KubeArmorHostPolicyLister.
type KubeArmorHostPolicyListerExpansion interface{}

// KubeArmorHostPolicyNamespaceListerExpansion allows custom methods to be added to
// KubeArmorHostPolicyNamespaceLister.
type KubeArmorHostPolicyNamespaceListerExpansion interface{}
