// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: policy.proto

package protobuf

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PolicyServiceClient is the client API for PolicyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PolicyServiceClient interface {
	ContainerPolicy(ctx context.Context, in *Policy, opts ...grpc.CallOption) (*Response, error)
	HostPolicy(ctx context.Context, in *Policy, opts ...grpc.CallOption) (*Response, error)
}

type policyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPolicyServiceClient(cc grpc.ClientConnInterface) PolicyServiceClient {
	return &policyServiceClient{cc}
}

func (c *policyServiceClient) ContainerPolicy(ctx context.Context, in *Policy, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/policy.PolicyService/containerPolicy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *policyServiceClient) HostPolicy(ctx context.Context, in *Policy, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/policy.PolicyService/hostPolicy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PolicyServiceServer is the server API for PolicyService service.
// All implementations must embed UnimplementedPolicyServiceServer
// for forward compatibility
type PolicyServiceServer interface {
	ContainerPolicy(context.Context, *Policy) (*Response, error)
	HostPolicy(context.Context, *Policy) (*Response, error)
	mustEmbedUnimplementedPolicyServiceServer()
}

// UnimplementedPolicyServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPolicyServiceServer struct {
}

func (UnimplementedPolicyServiceServer) ContainerPolicy(context.Context, *Policy) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ContainerPolicy not implemented")
}
func (UnimplementedPolicyServiceServer) HostPolicy(context.Context, *Policy) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HostPolicy not implemented")
}
func (UnimplementedPolicyServiceServer) mustEmbedUnimplementedPolicyServiceServer() {}

// UnsafePolicyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PolicyServiceServer will
// result in compilation errors.
type UnsafePolicyServiceServer interface {
	mustEmbedUnimplementedPolicyServiceServer()
}

func RegisterPolicyServiceServer(s grpc.ServiceRegistrar, srv PolicyServiceServer) {
	s.RegisterService(&PolicyService_ServiceDesc, srv)
}

func _PolicyService_ContainerPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Policy)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolicyServiceServer).ContainerPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/policy.PolicyService/containerPolicy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolicyServiceServer).ContainerPolicy(ctx, req.(*Policy))
	}
	return interceptor(ctx, in, info, handler)
}

func _PolicyService_HostPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Policy)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolicyServiceServer).HostPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/policy.PolicyService/hostPolicy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolicyServiceServer).HostPolicy(ctx, req.(*Policy))
	}
	return interceptor(ctx, in, info, handler)
}

// PolicyService_ServiceDesc is the grpc.ServiceDesc for PolicyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PolicyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "policy.PolicyService",
	HandlerType: (*PolicyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "containerPolicy",
			Handler:    _PolicyService_ContainerPolicy_Handler,
		},
		{
			MethodName: "hostPolicy",
			Handler:    _PolicyService_HostPolicy_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "policy.proto",
}

// PolicyStreamServiceClient is the client API for PolicyStreamService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PolicyStreamServiceClient interface {
	HealthCheck(ctx context.Context, in *HealthCheckReq, opts ...grpc.CallOption) (*HealthCheckReply, error)
	ContainerPolicy(ctx context.Context, opts ...grpc.CallOption) (PolicyStreamService_ContainerPolicyClient, error)
	HostPolicy(ctx context.Context, opts ...grpc.CallOption) (PolicyStreamService_HostPolicyClient, error)
}

type policyStreamServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPolicyStreamServiceClient(cc grpc.ClientConnInterface) PolicyStreamServiceClient {
	return &policyStreamServiceClient{cc}
}

func (c *policyStreamServiceClient) HealthCheck(ctx context.Context, in *HealthCheckReq, opts ...grpc.CallOption) (*HealthCheckReply, error) {
	out := new(HealthCheckReply)
	err := c.cc.Invoke(ctx, "/policy.PolicyStreamService/HealthCheck", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *policyStreamServiceClient) ContainerPolicy(ctx context.Context, opts ...grpc.CallOption) (PolicyStreamService_ContainerPolicyClient, error) {
	stream, err := c.cc.NewStream(ctx, &PolicyStreamService_ServiceDesc.Streams[0], "/policy.PolicyStreamService/containerPolicy", opts...)
	if err != nil {
		return nil, err
	}
	x := &policyStreamServiceContainerPolicyClient{stream}
	return x, nil
}

type PolicyStreamService_ContainerPolicyClient interface {
	Send(*Response) error
	Recv() (*Policy, error)
	grpc.ClientStream
}

type policyStreamServiceContainerPolicyClient struct {
	grpc.ClientStream
}

func (x *policyStreamServiceContainerPolicyClient) Send(m *Response) error {
	return x.ClientStream.SendMsg(m)
}

func (x *policyStreamServiceContainerPolicyClient) Recv() (*Policy, error) {
	m := new(Policy)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *policyStreamServiceClient) HostPolicy(ctx context.Context, opts ...grpc.CallOption) (PolicyStreamService_HostPolicyClient, error) {
	stream, err := c.cc.NewStream(ctx, &PolicyStreamService_ServiceDesc.Streams[1], "/policy.PolicyStreamService/hostPolicy", opts...)
	if err != nil {
		return nil, err
	}
	x := &policyStreamServiceHostPolicyClient{stream}
	return x, nil
}

type PolicyStreamService_HostPolicyClient interface {
	Send(*Response) error
	Recv() (*Policy, error)
	grpc.ClientStream
}

type policyStreamServiceHostPolicyClient struct {
	grpc.ClientStream
}

func (x *policyStreamServiceHostPolicyClient) Send(m *Response) error {
	return x.ClientStream.SendMsg(m)
}

func (x *policyStreamServiceHostPolicyClient) Recv() (*Policy, error) {
	m := new(Policy)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// PolicyStreamServiceServer is the server API for PolicyStreamService service.
// All implementations must embed UnimplementedPolicyStreamServiceServer
// for forward compatibility
type PolicyStreamServiceServer interface {
	HealthCheck(context.Context, *HealthCheckReq) (*HealthCheckReply, error)
	ContainerPolicy(PolicyStreamService_ContainerPolicyServer) error
	HostPolicy(PolicyStreamService_HostPolicyServer) error
	mustEmbedUnimplementedPolicyStreamServiceServer()
}

// UnimplementedPolicyStreamServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPolicyStreamServiceServer struct {
}

func (UnimplementedPolicyStreamServiceServer) HealthCheck(context.Context, *HealthCheckReq) (*HealthCheckReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedPolicyStreamServiceServer) ContainerPolicy(PolicyStreamService_ContainerPolicyServer) error {
	return status.Errorf(codes.Unimplemented, "method ContainerPolicy not implemented")
}
func (UnimplementedPolicyStreamServiceServer) HostPolicy(PolicyStreamService_HostPolicyServer) error {
	return status.Errorf(codes.Unimplemented, "method HostPolicy not implemented")
}
func (UnimplementedPolicyStreamServiceServer) mustEmbedUnimplementedPolicyStreamServiceServer() {}

// UnsafePolicyStreamServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PolicyStreamServiceServer will
// result in compilation errors.
type UnsafePolicyStreamServiceServer interface {
	mustEmbedUnimplementedPolicyStreamServiceServer()
}

func RegisterPolicyStreamServiceServer(s grpc.ServiceRegistrar, srv PolicyStreamServiceServer) {
	s.RegisterService(&PolicyStreamService_ServiceDesc, srv)
}

func _PolicyStreamService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolicyStreamServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/policy.PolicyStreamService/HealthCheck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolicyStreamServiceServer).HealthCheck(ctx, req.(*HealthCheckReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PolicyStreamService_ContainerPolicy_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PolicyStreamServiceServer).ContainerPolicy(&policyStreamServiceContainerPolicyServer{stream})
}

type PolicyStreamService_ContainerPolicyServer interface {
	Send(*Policy) error
	Recv() (*Response, error)
	grpc.ServerStream
}

type policyStreamServiceContainerPolicyServer struct {
	grpc.ServerStream
}

func (x *policyStreamServiceContainerPolicyServer) Send(m *Policy) error {
	return x.ServerStream.SendMsg(m)
}

func (x *policyStreamServiceContainerPolicyServer) Recv() (*Response, error) {
	m := new(Response)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _PolicyStreamService_HostPolicy_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PolicyStreamServiceServer).HostPolicy(&policyStreamServiceHostPolicyServer{stream})
}

type PolicyStreamService_HostPolicyServer interface {
	Send(*Policy) error
	Recv() (*Response, error)
	grpc.ServerStream
}

type policyStreamServiceHostPolicyServer struct {
	grpc.ServerStream
}

func (x *policyStreamServiceHostPolicyServer) Send(m *Policy) error {
	return x.ServerStream.SendMsg(m)
}

func (x *policyStreamServiceHostPolicyServer) Recv() (*Response, error) {
	m := new(Response)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// PolicyStreamService_ServiceDesc is the grpc.ServiceDesc for PolicyStreamService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PolicyStreamService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "policy.PolicyStreamService",
	HandlerType: (*PolicyStreamServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HealthCheck",
			Handler:    _PolicyStreamService_HealthCheck_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "containerPolicy",
			Handler:       _PolicyStreamService_ContainerPolicy_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "hostPolicy",
			Handler:       _PolicyStreamService_HostPolicy_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "policy.proto",
}
