// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.12.4
// source: state.proto

package protobuf

import (
	context "context"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	StateAgent_WatchState_FullMethodName = "/state_agent.StateAgent/WatchState"
	StateAgent_GetState_FullMethodName   = "/state_agent.StateAgent/GetState"
)

// StateAgentClient is the client API for StateAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StateAgentClient interface {
	// stream which continuously pushes state events
	WatchState(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (StateAgent_WatchStateClient, error)
	// get all state events in one go
	GetState(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (StateAgent_GetStateClient, error)
}

type stateAgentClient struct {
	cc grpc.ClientConnInterface
}

func NewStateAgentClient(cc grpc.ClientConnInterface) StateAgentClient {
	return &stateAgentClient{cc}
}

func (c *stateAgentClient) WatchState(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (StateAgent_WatchStateClient, error) {
	stream, err := c.cc.NewStream(ctx, &StateAgent_ServiceDesc.Streams[0], StateAgent_WatchState_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &stateAgentWatchStateClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type StateAgent_WatchStateClient interface {
	Recv() (*StateEvent, error)
	grpc.ClientStream
}

type stateAgentWatchStateClient struct {
	grpc.ClientStream
}

func (x *stateAgentWatchStateClient) Recv() (*StateEvent, error) {
	m := new(StateEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *stateAgentClient) GetState(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (StateAgent_GetStateClient, error) {
	stream, err := c.cc.NewStream(ctx, &StateAgent_ServiceDesc.Streams[1], StateAgent_GetState_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &stateAgentGetStateClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type StateAgent_GetStateClient interface {
	Recv() (*StateEvents, error)
	grpc.ClientStream
}

type stateAgentGetStateClient struct {
	grpc.ClientStream
}

func (x *stateAgentGetStateClient) Recv() (*StateEvents, error) {
	m := new(StateEvents)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// StateAgentServer is the server API for StateAgent service.
// All implementations should embed UnimplementedStateAgentServer
// for forward compatibility
type StateAgentServer interface {
	// stream which continuously pushes state events
	WatchState(*empty.Empty, StateAgent_WatchStateServer) error
	// get all state events in one go
	GetState(*empty.Empty, StateAgent_GetStateServer) error
}

// UnimplementedStateAgentServer should be embedded to have forward compatible implementations.
type UnimplementedStateAgentServer struct {
}

func (UnimplementedStateAgentServer) WatchState(*empty.Empty, StateAgent_WatchStateServer) error {
	return status.Errorf(codes.Unimplemented, "method WatchState not implemented")
}
func (UnimplementedStateAgentServer) GetState(*empty.Empty, StateAgent_GetStateServer) error {
	return status.Errorf(codes.Unimplemented, "method GetState not implemented")
}

// UnsafeStateAgentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StateAgentServer will
// result in compilation errors.
type UnsafeStateAgentServer interface {
	mustEmbedUnimplementedStateAgentServer()
}

func RegisterStateAgentServer(s grpc.ServiceRegistrar, srv StateAgentServer) {
	s.RegisterService(&StateAgent_ServiceDesc, srv)
}

func _StateAgent_WatchState_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(empty.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StateAgentServer).WatchState(m, &stateAgentWatchStateServer{stream})
}

type StateAgent_WatchStateServer interface {
	Send(*StateEvent) error
	grpc.ServerStream
}

type stateAgentWatchStateServer struct {
	grpc.ServerStream
}

func (x *stateAgentWatchStateServer) Send(m *StateEvent) error {
	return x.ServerStream.SendMsg(m)
}

func _StateAgent_GetState_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(empty.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StateAgentServer).GetState(m, &stateAgentGetStateServer{stream})
}

type StateAgent_GetStateServer interface {
	Send(*StateEvents) error
	grpc.ServerStream
}

type stateAgentGetStateServer struct {
	grpc.ServerStream
}

func (x *stateAgentGetStateServer) Send(m *StateEvents) error {
	return x.ServerStream.SendMsg(m)
}

// StateAgent_ServiceDesc is the grpc.ServiceDesc for StateAgent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StateAgent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "state_agent.StateAgent",
	HandlerType: (*StateAgentServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchState",
			Handler:       _StateAgent_WatchState_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetState",
			Handler:       _StateAgent_GetState_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "state.proto",
}
