// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: state.proto

package protobuf

import (
	empty "github.com/golang/protobuf/ptypes/empty"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StateEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=Kind,proto3" json:"Kind,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=Type,proto3" json:"Type,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	Object        []byte                 `protobuf:"bytes,4,opt,name=Object,proto3" json:"Object,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateEvent) Reset() {
	*x = StateEvent{}
	mi := &file_state_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateEvent) ProtoMessage() {}

func (x *StateEvent) ProtoReflect() protoreflect.Message {
	mi := &file_state_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateEvent.ProtoReflect.Descriptor instead.
func (*StateEvent) Descriptor() ([]byte, []int) {
	return file_state_proto_rawDescGZIP(), []int{0}
}

func (x *StateEvent) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *StateEvent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *StateEvent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StateEvent) GetObject() []byte {
	if x != nil {
		return x.Object
	}
	return nil
}

type StateEvents struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StateEvents   []*StateEvent          `protobuf:"bytes,1,rep,name=StateEvents,proto3" json:"StateEvents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateEvents) Reset() {
	*x = StateEvents{}
	mi := &file_state_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateEvents) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateEvents) ProtoMessage() {}

func (x *StateEvents) ProtoReflect() protoreflect.Message {
	mi := &file_state_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateEvents.ProtoReflect.Descriptor instead.
func (*StateEvents) Descriptor() ([]byte, []int) {
	return file_state_proto_rawDescGZIP(), []int{1}
}

func (x *StateEvents) GetStateEvents() []*StateEvent {
	if x != nil {
		return x.StateEvents
	}
	return nil
}

var File_state_proto protoreflect.FileDescriptor

const file_state_proto_rawDesc = "" +
	"\n" +
	"\vstate.proto\x12\vstate_agent\x1a\x1bgoogle/protobuf/empty.proto\"`\n" +
	"\n" +
	"StateEvent\x12\x12\n" +
	"\x04Kind\x18\x01 \x01(\tR\x04Kind\x12\x12\n" +
	"\x04Type\x18\x02 \x01(\tR\x04Type\x12\x12\n" +
	"\x04Name\x18\x03 \x01(\tR\x04Name\x12\x16\n" +
	"\x06Object\x18\x04 \x01(\fR\x06Object\"H\n" +
	"\vStateEvents\x129\n" +
	"\vStateEvents\x18\x01 \x03(\v2\x17.state_agent.StateEventR\vStateEvents2\x8d\x01\n" +
	"\n" +
	"StateAgent\x12?\n" +
	"\n" +
	"WatchState\x12\x16.google.protobuf.Empty\x1a\x17.state_agent.StateEvent0\x01\x12>\n" +
	"\bGetState\x12\x16.google.protobuf.Empty\x1a\x18.state_agent.StateEvents0\x01B)Z'github.com/kubearmor/KubeArmor/protobufb\x06proto3"

var (
	file_state_proto_rawDescOnce sync.Once
	file_state_proto_rawDescData []byte
)

func file_state_proto_rawDescGZIP() []byte {
	file_state_proto_rawDescOnce.Do(func() {
		file_state_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_state_proto_rawDesc), len(file_state_proto_rawDesc)))
	})
	return file_state_proto_rawDescData
}

var file_state_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_state_proto_goTypes = []any{
	(*StateEvent)(nil),  // 0: state_agent.StateEvent
	(*StateEvents)(nil), // 1: state_agent.StateEvents
	(*empty.Empty)(nil), // 2: google.protobuf.Empty
}
var file_state_proto_depIdxs = []int32{
	0, // 0: state_agent.StateEvents.StateEvents:type_name -> state_agent.StateEvent
	2, // 1: state_agent.StateAgent.WatchState:input_type -> google.protobuf.Empty
	2, // 2: state_agent.StateAgent.GetState:input_type -> google.protobuf.Empty
	0, // 3: state_agent.StateAgent.WatchState:output_type -> state_agent.StateEvent
	1, // 4: state_agent.StateAgent.GetState:output_type -> state_agent.StateEvents
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_state_proto_init() }
func file_state_proto_init() {
	if File_state_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_state_proto_rawDesc), len(file_state_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_state_proto_goTypes,
		DependencyIndexes: file_state_proto_depIdxs,
		MessageInfos:      file_state_proto_msgTypes,
	}.Build()
	File_state_proto = out.File
	file_state_proto_goTypes = nil
	file_state_proto_depIdxs = nil
}
