Vagrant.require_version ">= 2.0.0"

Vagrant.configure("2") do |config|
  config.vm.define "KubeArmor-Dev" do |cfg|
    cfg.vm.box = "ubuntu/bionic64"
    cfg.vm.provider "virtualbox" do |vb|
      vb.name = "KubeArmor-Dev"
      vb.memory = "4096"
      vb.cpus = 4
      vb.customize ['modifyvm', :id, '--nested-hw-virt', 'on']
    end
  end

  # vagrant@kubearmor-dev
  config.vm.hostname = "kubearmor-dev"

  # sync directories
  kubearmor_home = "../.."
  config.vm.synced_folder kubearmor_home, "/home/vagrant/KubeArmor"

  # copy ssh keys
  config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "/home/vagrant/.ssh/id_rsa.pub"
  config.vm.provision :shell, :inline => "cat /home/vagrant/.ssh/id_rsa.pub >> /home/vagrant/.ssh/authorized_keys", run: "always"

  # copy git config
  config.vm.provision :file, source: "~/.gitconfig", destination: "$HOME/.gitconfig"

  # Provision bash scripts
  config.vm.provision :shell, path: kubearmor_home + "/contributions/self-managed-k8s/setup.sh"
  config.vm.provision :shell, path: kubearmor_home + "/contributions/self-managed-k8s/docker/install_docker.sh"
  config.vm.provision :shell, path: kubearmor_home + "/contributions/self-managed-k8s/k8s/install_kubernetes.sh"

  # Initialize Kubernetes
  config.vm.provision :shell, path: kubearmor_home + "/contributions/self-managed-k8s/k8s/initialize_kubernetes.sh"
end
