// Code generated by bpf2go; DO NOT EDIT.
//go:build arm64

package apiobserver

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type apiObserverArgBufsK struct {
	_    structs.HostLayout
	Okey struct {
		_     structs.HostLayout
		PidNs uint32
		MntNs uint32
	}
	Store apiObserverBufsK
	Arg   [104]int8
}

type apiObserverArgVal struct {
	_         structs.HostLayout
	ArgsArray [104]int8
}

type apiObserverBufsK struct {
	_      structs.HostLayout
	Path   [200]int8
	Source [200]int8
}

type apiObserverBufsT struct {
	_   structs.HostLayout
	Buf [32768]int8
}

type apiObserverCmdArgsKey struct {
	_    structs.HostLayout
	Tgid uint64
	Ind  uint64
}

type apiObserverGoAddrKey struct {
	_    structs.HostLayout
	Addr uint64
	Pid  uint32
	Pad  uint32
}

type apiObserverGoGrpcClientInvocation struct {
	_         structs.HostLayout
	StartNs   uint64
	MethodPtr uint64
	MethodLen uint64
}

type apiObserverGoGrpcServerInvocation struct {
	_         structs.HostLayout
	StartNs   uint64
	StreamPtr uint64
}

type apiObserverGoH2EncoderCtx struct {
	_        structs.HostLayout
	Pid      uint32
	StreamId uint32
}

type apiObserverGoH2SingleHeaderEvent struct {
	_         structs.HostLayout
	Pid       uint32
	StreamId  uint32
	IsServer  uint8
	EventType uint8
	NameLen   uint16
	ValueLen  uint16
	Pad       uint16
	Name      [128]int8
	Value     [128]int8
}

type apiObserverGoH2TransportEvent struct {
	_          structs.HostLayout
	Pid        uint32
	StreamId   uint32
	IsServer   uint8
	FieldCount uint8
	Pad        uint16
	Fields     [20]struct {
		_     structs.HostLayout
		Name  [128]int8
		Value [128]int8
	}
}

type apiObserverGoOffsetTable struct {
	_       structs.HostLayout
	Offsets [26]int64
}

type apiObserverGrpccSymaddrs struct {
	_                  structs.HostLayout
	StreamMethodOffset int32
	StreamIdOffset     int32
	TransportFdOffset  int32
}

type apiObserverKaConfiguration struct {
	_     structs.HostLayout
	Flags uint32
	Pad   uint32
}

type apiObserverKaFoundPid struct {
	_        structs.HostLayout
	CgroupId uint64
	Tgid     uint32
	Pad      uint32
}

type apiObserverKaPkt struct {
	_         structs.HostLayout
	Timestamp uint64
	CgroupId  uint64
	Id        uint64
	Len       uint32
	TotLen    uint32
	Counter   uint32
	Num       uint16
	Last      uint16
	IpHdrType uint16
	Direction uint8
	Pad       [1]uint8
	Buf       [4080]uint8
	_         [4]byte
}

type apiObserverKaPktIdT struct {
	_    structs.HostLayout
	Id   uint64
	Lock struct {
		_   structs.HostLayout
		Val uint32
	}
	_ [4]byte
}

type apiObserverKsAcceptInfo struct {
	_       structs.HostLayout
	Addrlen uint64
}

type apiObserverKsAddressInfo struct {
	_      structs.HostLayout
	Family uint32
	Saddr4 uint32
	Daddr4 uint32
	Saddr6 [16]uint8
	Daddr6 [16]uint8
	Sport  uint16
	Dport  uint16
}

type apiObserverKsConnectInfo struct {
	_       structs.HostLayout
	Fd      uint64
	Addrlen uint32
	_       [4]byte
}

type apiObserverKsGoTlsSymaddrs struct {
	_                structs.HostLayout
	ConnDataOffset   uint64
	NetfdSysfdOffset uint64
}

type apiObserverKsSslInfo struct {
	_             structs.HostLayout
	Buffer        uint64
	BufferLen     uint32
	Fd            uint32
	CreatedAtNano uint64
	AddressInfo   apiObserverKsAddressInfo
	CountPtr      uint64
}

type apiObserverKsTlsChunk struct {
	_           structs.HostLayout
	Timestamp   uint64
	CgroupId    uint32
	Pid         uint32
	Tgid        uint32
	Len         uint32
	Start       uint32
	Recorded    uint32
	Fd          uint32
	Flags       uint32
	AddressInfo apiObserverKsAddressInfo
	Data        [4096]uint8
}

type apiObserverSslSymaddrs struct {
	_             structs.HostLayout
	SslRbioOffset int32
	BioNumOffset  int32
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	apiObserverMapArgsBufk                                = "args_bufk"
	apiObserverMapBufk                                    = "bufk"
	apiObserverMapBufs                                    = "bufs"
	apiObserverMapBufsOff                                 = "bufs_off"
	apiObserverMapCmdArgsBuf                              = "cmd_args_buf"
	apiObserverMapGoH2ActiveEncoderMap                    = "go_h2_active_encoder_map"
	apiObserverMapGoH2SingleHeaderEvents                  = "go_h2_single_header_events"
	apiObserverMapGoH2SingleHeaderScratch                 = "go_h2_single_header_scratch"
	apiObserverMapGoH2TransportEvents                     = "go_h2_transport_events"
	apiObserverMapGoH2TransportScratch                    = "go_h2_transport_scratch"
	apiObserverMapGoHttp2Events                           = "go_http2_events"
	apiObserverMapGoOffsetsMap                            = "go_offsets_map"
	apiObserverMapGrpccEvents                             = "grpcc_events"
	apiObserverMapGrpccSymaddrsMap                        = "grpcc_symaddrs_map"
	apiObserverMapKaCgroupIds                             = "ka_cgroup_ids"
	apiObserverMapKaExcludedCgroupIds                     = "ka_excluded_cgroup_ids"
	apiObserverMapKaForkInfo                              = "ka_fork_info"
	apiObserverMapKaFoundPidEvents                        = "ka_found_pid_events"
	apiObserverMapKaPktHeap                               = "ka_pkt_heap"
	apiObserverMapKaPktHeapHash                           = "ka_pkt_heap_hash"
	apiObserverMapKaPktId                                 = "ka_pkt_id"
	apiObserverMapKaPktsBuffer                            = "ka_pkts_buffer"
	apiObserverMapKaSettings                              = "ka_settings"
	apiObserverMapKaSocketCgroups                         = "ka_socket_cgroups"
	apiObserverMapKsAcceptSyscallContext                  = "ks_accept_syscall_context"
	apiObserverMapKsChunksBuffer                          = "ks_chunks_buffer"
	apiObserverMapKsConnectSyscallInfo                    = "ks_connect_syscall_info"
	apiObserverMapKsConnectionContext                     = "ks_connection_context"
	apiObserverMapKsGoKernelReadContext                   = "ks_go_kernel_read_context"
	apiObserverMapKsGoKernelWriteContext                  = "ks_go_kernel_write_context"
	apiObserverMapKsGoReadContext                         = "ks_go_read_context"
	apiObserverMapKsGoTlsFdOffsets                        = "ks_go_tls_fd_offsets"
	apiObserverMapKsGoUserKernelReadContext               = "ks_go_user_kernel_read_context"
	apiObserverMapKsGoUserKernelWriteContext              = "ks_go_user_kernel_write_context"
	apiObserverMapKsGoWriteContext                        = "ks_go_write_context"
	apiObserverMapKsHeap                                  = "ks_heap"
	apiObserverMapKsOpensslConnAddr                       = "ks_openssl_conn_addr"
	apiObserverMapKsOpensslReadContext                    = "ks_openssl_read_context"
	apiObserverMapKsOpensslWriteContext                   = "ks_openssl_write_context"
	apiObserverMapKsPidLastSocketFd                       = "ks_pid_last_socket_fd"
	apiObserverMapKsTgidLastSocketFd                      = "ks_tgid_last_socket_fd"
	apiObserverMapKubearmorAlertThrottle                  = "kubearmor_alert_throttle"
	apiObserverMapKubearmorArgsStore                      = "kubearmor_args_store"
	apiObserverMapKubearmorArguments                      = "kubearmor_arguments"
	apiObserverMapKubearmorConfig                         = "kubearmor_config"
	apiObserverMapKubearmorContainers                     = "kubearmor_containers"
	apiObserverMapKubearmorEvents                         = "kubearmor_events"
	apiObserverMapKubearmorExecPids                       = "kubearmor_exec_pids"
	apiObserverMapNsCgroupMap                             = "ns_cgroup_map"
	apiObserverMapNsFilterConfig                          = "ns_filter_config"
	apiObserverMapOngoingGrpcClientRequests               = "ongoing_grpc_client_requests"
	apiObserverMapOngoingGrpcRequestStatus                = "ongoing_grpc_request_status"
	apiObserverMapOngoingGrpcServerRequests               = "ongoing_grpc_server_requests"
	apiObserverMapPortExclusionMap                        = "port_exclusion_map"
	apiObserverMapSslSymaddrs                             = "ssl_symaddrs"
	apiObserverProgKaFilterEgressPackets                  = "ka_filter_egress_packets"
	apiObserverProgKaFilterIngressPackets                 = "ka_filter_ingress_packets"
	apiObserverProgKaKretprobeSysExecve                   = "ka_kretprobe_sys_execve"
	apiObserverProgKaSchedProcessFork                     = "ka_sched_process_fork"
	apiObserverProgKaUprobeClientConnInvoke               = "ka_uprobe_ClientConn_Invoke"
	apiObserverProgKaUprobeClientConnNewStream            = "ka_uprobe_ClientConn_NewStream"
	apiObserverProgKaUprobeGoTlsRead                      = "ka_uprobe_go_tls_read"
	apiObserverProgKaUprobeGoTlsReadEx                    = "ka_uprobe_go_tls_read_ex"
	apiObserverProgKaUprobeGoTlsWrite                     = "ka_uprobe_go_tls_write"
	apiObserverProgKaUprobeGoTlsWriteEx                   = "ka_uprobe_go_tls_write_ex"
	apiObserverProgKaUprobeGrpcC_recvInitialMetadataEntry = "ka_uprobe_grpc_c_recv_initial_metadata_entry"
	apiObserverProgKaUprobeHpackWriteField                = "ka_uprobe_hpack_write_field"
	apiObserverProgKaUprobeHttp2WriteResHeaders           = "ka_uprobe_http2_write_res_headers"
	apiObserverProgKaUprobeLoopyWriterWriteHeader         = "ka_uprobe_loopy_writer_write_header"
	apiObserverProgKaUprobeNetHttpProcessHeaders          = "ka_uprobe_net_http_processHeaders"
	apiObserverProgKaUprobeOperateHeadersClient           = "ka_uprobe_operate_headers_client"
	apiObserverProgKaUprobeOperateHeadersClientEntry      = "ka_uprobe_operate_headers_client_entry"
	apiObserverProgKaUprobeOperateHeadersServer           = "ka_uprobe_operate_headers_server"
	apiObserverProgKaUprobeOperateHeadersServerEntry      = "ka_uprobe_operate_headers_server_entry"
	apiObserverProgKaUprobeServerHandleStream             = "ka_uprobe_server_handleStream"
	apiObserverProgKaUprobeTransportWriteStatus           = "ka_uprobe_transport_writeStatus"
	apiObserverProgKaUretprobeClientConnInvoke            = "ka_uretprobe_ClientConn_Invoke"
	apiObserverProgKaUretprobeClientStreamRecvMsg         = "ka_uretprobe_clientStream_RecvMsg"
	apiObserverProgKaUretprobeServerHandleStream          = "ka_uretprobe_server_handleStream"
	apiObserverProgKsKprobeTcpRecvmsg                     = "ks_kprobe_tcp_recvmsg"
	apiObserverProgKsKprobeTcpSendmsg                     = "ks_kprobe_tcp_sendmsg"
	apiObserverProgKsSslPending                           = "ks_ssl_pending"
	apiObserverProgKsSslRead                              = "ks_ssl_read"
	apiObserverProgKsSslReadEx                            = "ks_ssl_read_ex"
	apiObserverProgKsSslRetRead                           = "ks_ssl_ret_read"
	apiObserverProgKsSslRetReadEx                         = "ks_ssl_ret_read_ex"
	apiObserverProgKsSslRetWrite                          = "ks_ssl_ret_write"
	apiObserverProgKsSslRetWriteEx                        = "ks_ssl_ret_write_ex"
	apiObserverProgKsSslWrite                             = "ks_ssl_write"
	apiObserverProgKsSslWriteEx                           = "ks_ssl_write_ex"
	apiObserverProgKsSysEnterAccept4                      = "ks_sys_enter_accept4"
	apiObserverProgKsSysEnterConnect                      = "ks_sys_enter_connect"
	apiObserverProgKsSysEnterRead                         = "ks_sys_enter_read"
	apiObserverProgKsSysEnterReadv                        = "ks_sys_enter_readv"
	apiObserverProgKsSysEnterRecvfrom                     = "ks_sys_enter_recvfrom"
	apiObserverProgKsSysEnterRecvmsg                      = "ks_sys_enter_recvmsg"
	apiObserverProgKsSysEnterSendmsg                      = "ks_sys_enter_sendmsg"
	apiObserverProgKsSysEnterSendto                       = "ks_sys_enter_sendto"
	apiObserverProgKsSysEnterWrite                        = "ks_sys_enter_write"
	apiObserverProgKsSysEnterWritev                       = "ks_sys_enter_writev"
	apiObserverProgKsSysExitAccept4                       = "ks_sys_exit_accept4"
	apiObserverProgKsSysExitConnect                       = "ks_sys_exit_connect"
	apiObserverProgKsSysExitRead                          = "ks_sys_exit_read"
	apiObserverProgKsSysExitWrite                         = "ks_sys_exit_write"
	apiObserverVarKsInvalidFd                             = "ks_invalid_fd"
)

// loadApiObserver returns the embedded CollectionSpec for apiObserver.
func loadApiObserver() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_ApiObserverBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load apiObserver: %w", err)
	}

	return spec, err
}

// loadApiObserverObjects loads apiObserver and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*apiObserverObjects
//	*apiObserverPrograms
//	*apiObserverMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadApiObserverObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadApiObserver()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// apiObserverSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type apiObserverSpecs struct {
	apiObserverProgramSpecs
	apiObserverMapSpecs
	apiObserverVariableSpecs
}

// apiObserverProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type apiObserverProgramSpecs struct {
	KaFilterEgressPackets                  *ebpf.ProgramSpec `ebpf:"ka_filter_egress_packets"`
	KaFilterIngressPackets                 *ebpf.ProgramSpec `ebpf:"ka_filter_ingress_packets"`
	KaKretprobeSysExecve                   *ebpf.ProgramSpec `ebpf:"ka_kretprobe_sys_execve"`
	KaSchedProcessFork                     *ebpf.ProgramSpec `ebpf:"ka_sched_process_fork"`
	KaUprobeClientConnInvoke               *ebpf.ProgramSpec `ebpf:"ka_uprobe_ClientConn_Invoke"`
	KaUprobeClientConnNewStream            *ebpf.ProgramSpec `ebpf:"ka_uprobe_ClientConn_NewStream"`
	KaUprobeGoTlsRead                      *ebpf.ProgramSpec `ebpf:"ka_uprobe_go_tls_read"`
	KaUprobeGoTlsReadEx                    *ebpf.ProgramSpec `ebpf:"ka_uprobe_go_tls_read_ex"`
	KaUprobeGoTlsWrite                     *ebpf.ProgramSpec `ebpf:"ka_uprobe_go_tls_write"`
	KaUprobeGoTlsWriteEx                   *ebpf.ProgramSpec `ebpf:"ka_uprobe_go_tls_write_ex"`
	KaUprobeGrpcC_recvInitialMetadataEntry *ebpf.ProgramSpec `ebpf:"ka_uprobe_grpc_c_recv_initial_metadata_entry"`
	KaUprobeHpackWriteField                *ebpf.ProgramSpec `ebpf:"ka_uprobe_hpack_write_field"`
	KaUprobeHttp2WriteResHeaders           *ebpf.ProgramSpec `ebpf:"ka_uprobe_http2_write_res_headers"`
	KaUprobeLoopyWriterWriteHeader         *ebpf.ProgramSpec `ebpf:"ka_uprobe_loopy_writer_write_header"`
	KaUprobeNetHttpProcessHeaders          *ebpf.ProgramSpec `ebpf:"ka_uprobe_net_http_processHeaders"`
	KaUprobeOperateHeadersClient           *ebpf.ProgramSpec `ebpf:"ka_uprobe_operate_headers_client"`
	KaUprobeOperateHeadersClientEntry      *ebpf.ProgramSpec `ebpf:"ka_uprobe_operate_headers_client_entry"`
	KaUprobeOperateHeadersServer           *ebpf.ProgramSpec `ebpf:"ka_uprobe_operate_headers_server"`
	KaUprobeOperateHeadersServerEntry      *ebpf.ProgramSpec `ebpf:"ka_uprobe_operate_headers_server_entry"`
	KaUprobeServerHandleStream             *ebpf.ProgramSpec `ebpf:"ka_uprobe_server_handleStream"`
	KaUprobeTransportWriteStatus           *ebpf.ProgramSpec `ebpf:"ka_uprobe_transport_writeStatus"`
	KaUretprobeClientConnInvoke            *ebpf.ProgramSpec `ebpf:"ka_uretprobe_ClientConn_Invoke"`
	KaUretprobeClientStreamRecvMsg         *ebpf.ProgramSpec `ebpf:"ka_uretprobe_clientStream_RecvMsg"`
	KaUretprobeServerHandleStream          *ebpf.ProgramSpec `ebpf:"ka_uretprobe_server_handleStream"`
	KsKprobeTcpRecvmsg                     *ebpf.ProgramSpec `ebpf:"ks_kprobe_tcp_recvmsg"`
	KsKprobeTcpSendmsg                     *ebpf.ProgramSpec `ebpf:"ks_kprobe_tcp_sendmsg"`
	KsSslPending                           *ebpf.ProgramSpec `ebpf:"ks_ssl_pending"`
	KsSslRead                              *ebpf.ProgramSpec `ebpf:"ks_ssl_read"`
	KsSslReadEx                            *ebpf.ProgramSpec `ebpf:"ks_ssl_read_ex"`
	KsSslRetRead                           *ebpf.ProgramSpec `ebpf:"ks_ssl_ret_read"`
	KsSslRetReadEx                         *ebpf.ProgramSpec `ebpf:"ks_ssl_ret_read_ex"`
	KsSslRetWrite                          *ebpf.ProgramSpec `ebpf:"ks_ssl_ret_write"`
	KsSslRetWriteEx                        *ebpf.ProgramSpec `ebpf:"ks_ssl_ret_write_ex"`
	KsSslWrite                             *ebpf.ProgramSpec `ebpf:"ks_ssl_write"`
	KsSslWriteEx                           *ebpf.ProgramSpec `ebpf:"ks_ssl_write_ex"`
	KsSysEnterAccept4                      *ebpf.ProgramSpec `ebpf:"ks_sys_enter_accept4"`
	KsSysEnterConnect                      *ebpf.ProgramSpec `ebpf:"ks_sys_enter_connect"`
	KsSysEnterRead                         *ebpf.ProgramSpec `ebpf:"ks_sys_enter_read"`
	KsSysEnterReadv                        *ebpf.ProgramSpec `ebpf:"ks_sys_enter_readv"`
	KsSysEnterRecvfrom                     *ebpf.ProgramSpec `ebpf:"ks_sys_enter_recvfrom"`
	KsSysEnterRecvmsg                      *ebpf.ProgramSpec `ebpf:"ks_sys_enter_recvmsg"`
	KsSysEnterSendmsg                      *ebpf.ProgramSpec `ebpf:"ks_sys_enter_sendmsg"`
	KsSysEnterSendto                       *ebpf.ProgramSpec `ebpf:"ks_sys_enter_sendto"`
	KsSysEnterWrite                        *ebpf.ProgramSpec `ebpf:"ks_sys_enter_write"`
	KsSysEnterWritev                       *ebpf.ProgramSpec `ebpf:"ks_sys_enter_writev"`
	KsSysExitAccept4                       *ebpf.ProgramSpec `ebpf:"ks_sys_exit_accept4"`
	KsSysExitConnect                       *ebpf.ProgramSpec `ebpf:"ks_sys_exit_connect"`
	KsSysExitRead                          *ebpf.ProgramSpec `ebpf:"ks_sys_exit_read"`
	KsSysExitWrite                         *ebpf.ProgramSpec `ebpf:"ks_sys_exit_write"`
}

// apiObserverMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type apiObserverMapSpecs struct {
	ArgsBufk                   *ebpf.MapSpec `ebpf:"args_bufk"`
	Bufk                       *ebpf.MapSpec `ebpf:"bufk"`
	Bufs                       *ebpf.MapSpec `ebpf:"bufs"`
	BufsOff                    *ebpf.MapSpec `ebpf:"bufs_off"`
	CmdArgsBuf                 *ebpf.MapSpec `ebpf:"cmd_args_buf"`
	GoH2ActiveEncoderMap       *ebpf.MapSpec `ebpf:"go_h2_active_encoder_map"`
	GoH2SingleHeaderEvents     *ebpf.MapSpec `ebpf:"go_h2_single_header_events"`
	GoH2SingleHeaderScratch    *ebpf.MapSpec `ebpf:"go_h2_single_header_scratch"`
	GoH2TransportEvents        *ebpf.MapSpec `ebpf:"go_h2_transport_events"`
	GoH2TransportScratch       *ebpf.MapSpec `ebpf:"go_h2_transport_scratch"`
	GoHttp2Events              *ebpf.MapSpec `ebpf:"go_http2_events"`
	GoOffsetsMap               *ebpf.MapSpec `ebpf:"go_offsets_map"`
	GrpccEvents                *ebpf.MapSpec `ebpf:"grpcc_events"`
	GrpccSymaddrsMap           *ebpf.MapSpec `ebpf:"grpcc_symaddrs_map"`
	KaCgroupIds                *ebpf.MapSpec `ebpf:"ka_cgroup_ids"`
	KaExcludedCgroupIds        *ebpf.MapSpec `ebpf:"ka_excluded_cgroup_ids"`
	KaForkInfo                 *ebpf.MapSpec `ebpf:"ka_fork_info"`
	KaFoundPidEvents           *ebpf.MapSpec `ebpf:"ka_found_pid_events"`
	KaPktHeap                  *ebpf.MapSpec `ebpf:"ka_pkt_heap"`
	KaPktHeapHash              *ebpf.MapSpec `ebpf:"ka_pkt_heap_hash"`
	KaPktId                    *ebpf.MapSpec `ebpf:"ka_pkt_id"`
	KaPktsBuffer               *ebpf.MapSpec `ebpf:"ka_pkts_buffer"`
	KaSettings                 *ebpf.MapSpec `ebpf:"ka_settings"`
	KaSocketCgroups            *ebpf.MapSpec `ebpf:"ka_socket_cgroups"`
	KsAcceptSyscallContext     *ebpf.MapSpec `ebpf:"ks_accept_syscall_context"`
	KsChunksBuffer             *ebpf.MapSpec `ebpf:"ks_chunks_buffer"`
	KsConnectSyscallInfo       *ebpf.MapSpec `ebpf:"ks_connect_syscall_info"`
	KsConnectionContext        *ebpf.MapSpec `ebpf:"ks_connection_context"`
	KsGoKernelReadContext      *ebpf.MapSpec `ebpf:"ks_go_kernel_read_context"`
	KsGoKernelWriteContext     *ebpf.MapSpec `ebpf:"ks_go_kernel_write_context"`
	KsGoReadContext            *ebpf.MapSpec `ebpf:"ks_go_read_context"`
	KsGoTlsFdOffsets           *ebpf.MapSpec `ebpf:"ks_go_tls_fd_offsets"`
	KsGoUserKernelReadContext  *ebpf.MapSpec `ebpf:"ks_go_user_kernel_read_context"`
	KsGoUserKernelWriteContext *ebpf.MapSpec `ebpf:"ks_go_user_kernel_write_context"`
	KsGoWriteContext           *ebpf.MapSpec `ebpf:"ks_go_write_context"`
	KsHeap                     *ebpf.MapSpec `ebpf:"ks_heap"`
	KsOpensslConnAddr          *ebpf.MapSpec `ebpf:"ks_openssl_conn_addr"`
	KsOpensslReadContext       *ebpf.MapSpec `ebpf:"ks_openssl_read_context"`
	KsOpensslWriteContext      *ebpf.MapSpec `ebpf:"ks_openssl_write_context"`
	KsPidLastSocketFd          *ebpf.MapSpec `ebpf:"ks_pid_last_socket_fd"`
	KsTgidLastSocketFd         *ebpf.MapSpec `ebpf:"ks_tgid_last_socket_fd"`
	KubearmorAlertThrottle     *ebpf.MapSpec `ebpf:"kubearmor_alert_throttle"`
	KubearmorArgsStore         *ebpf.MapSpec `ebpf:"kubearmor_args_store"`
	KubearmorArguments         *ebpf.MapSpec `ebpf:"kubearmor_arguments"`
	KubearmorConfig            *ebpf.MapSpec `ebpf:"kubearmor_config"`
	KubearmorContainers        *ebpf.MapSpec `ebpf:"kubearmor_containers"`
	KubearmorEvents            *ebpf.MapSpec `ebpf:"kubearmor_events"`
	KubearmorExecPids          *ebpf.MapSpec `ebpf:"kubearmor_exec_pids"`
	NsCgroupMap                *ebpf.MapSpec `ebpf:"ns_cgroup_map"`
	NsFilterConfig             *ebpf.MapSpec `ebpf:"ns_filter_config"`
	OngoingGrpcClientRequests  *ebpf.MapSpec `ebpf:"ongoing_grpc_client_requests"`
	OngoingGrpcRequestStatus   *ebpf.MapSpec `ebpf:"ongoing_grpc_request_status"`
	OngoingGrpcServerRequests  *ebpf.MapSpec `ebpf:"ongoing_grpc_server_requests"`
	PortExclusionMap           *ebpf.MapSpec `ebpf:"port_exclusion_map"`
	SslSymaddrs                *ebpf.MapSpec `ebpf:"ssl_symaddrs"`
}

// apiObserverVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type apiObserverVariableSpecs struct {
	KsInvalidFd *ebpf.VariableSpec `ebpf:"ks_invalid_fd"`
}

// apiObserverObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadApiObserverObjects or ebpf.CollectionSpec.LoadAndAssign.
type apiObserverObjects struct {
	apiObserverPrograms
	apiObserverMaps
	apiObserverVariables
}

func (o *apiObserverObjects) Close() error {
	return _ApiObserverClose(
		&o.apiObserverPrograms,
		&o.apiObserverMaps,
	)
}

// apiObserverMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadApiObserverObjects or ebpf.CollectionSpec.LoadAndAssign.
type apiObserverMaps struct {
	ArgsBufk                   *ebpf.Map `ebpf:"args_bufk"`
	Bufk                       *ebpf.Map `ebpf:"bufk"`
	Bufs                       *ebpf.Map `ebpf:"bufs"`
	BufsOff                    *ebpf.Map `ebpf:"bufs_off"`
	CmdArgsBuf                 *ebpf.Map `ebpf:"cmd_args_buf"`
	GoH2ActiveEncoderMap       *ebpf.Map `ebpf:"go_h2_active_encoder_map"`
	GoH2SingleHeaderEvents     *ebpf.Map `ebpf:"go_h2_single_header_events"`
	GoH2SingleHeaderScratch    *ebpf.Map `ebpf:"go_h2_single_header_scratch"`
	GoH2TransportEvents        *ebpf.Map `ebpf:"go_h2_transport_events"`
	GoH2TransportScratch       *ebpf.Map `ebpf:"go_h2_transport_scratch"`
	GoHttp2Events              *ebpf.Map `ebpf:"go_http2_events"`
	GoOffsetsMap               *ebpf.Map `ebpf:"go_offsets_map"`
	GrpccEvents                *ebpf.Map `ebpf:"grpcc_events"`
	GrpccSymaddrsMap           *ebpf.Map `ebpf:"grpcc_symaddrs_map"`
	KaCgroupIds                *ebpf.Map `ebpf:"ka_cgroup_ids"`
	KaExcludedCgroupIds        *ebpf.Map `ebpf:"ka_excluded_cgroup_ids"`
	KaForkInfo                 *ebpf.Map `ebpf:"ka_fork_info"`
	KaFoundPidEvents           *ebpf.Map `ebpf:"ka_found_pid_events"`
	KaPktHeap                  *ebpf.Map `ebpf:"ka_pkt_heap"`
	KaPktHeapHash              *ebpf.Map `ebpf:"ka_pkt_heap_hash"`
	KaPktId                    *ebpf.Map `ebpf:"ka_pkt_id"`
	KaPktsBuffer               *ebpf.Map `ebpf:"ka_pkts_buffer"`
	KaSettings                 *ebpf.Map `ebpf:"ka_settings"`
	KaSocketCgroups            *ebpf.Map `ebpf:"ka_socket_cgroups"`
	KsAcceptSyscallContext     *ebpf.Map `ebpf:"ks_accept_syscall_context"`
	KsChunksBuffer             *ebpf.Map `ebpf:"ks_chunks_buffer"`
	KsConnectSyscallInfo       *ebpf.Map `ebpf:"ks_connect_syscall_info"`
	KsConnectionContext        *ebpf.Map `ebpf:"ks_connection_context"`
	KsGoKernelReadContext      *ebpf.Map `ebpf:"ks_go_kernel_read_context"`
	KsGoKernelWriteContext     *ebpf.Map `ebpf:"ks_go_kernel_write_context"`
	KsGoReadContext            *ebpf.Map `ebpf:"ks_go_read_context"`
	KsGoTlsFdOffsets           *ebpf.Map `ebpf:"ks_go_tls_fd_offsets"`
	KsGoUserKernelReadContext  *ebpf.Map `ebpf:"ks_go_user_kernel_read_context"`
	KsGoUserKernelWriteContext *ebpf.Map `ebpf:"ks_go_user_kernel_write_context"`
	KsGoWriteContext           *ebpf.Map `ebpf:"ks_go_write_context"`
	KsHeap                     *ebpf.Map `ebpf:"ks_heap"`
	KsOpensslConnAddr          *ebpf.Map `ebpf:"ks_openssl_conn_addr"`
	KsOpensslReadContext       *ebpf.Map `ebpf:"ks_openssl_read_context"`
	KsOpensslWriteContext      *ebpf.Map `ebpf:"ks_openssl_write_context"`
	KsPidLastSocketFd          *ebpf.Map `ebpf:"ks_pid_last_socket_fd"`
	KsTgidLastSocketFd         *ebpf.Map `ebpf:"ks_tgid_last_socket_fd"`
	KubearmorAlertThrottle     *ebpf.Map `ebpf:"kubearmor_alert_throttle"`
	KubearmorArgsStore         *ebpf.Map `ebpf:"kubearmor_args_store"`
	KubearmorArguments         *ebpf.Map `ebpf:"kubearmor_arguments"`
	KubearmorConfig            *ebpf.Map `ebpf:"kubearmor_config"`
	KubearmorContainers        *ebpf.Map `ebpf:"kubearmor_containers"`
	KubearmorEvents            *ebpf.Map `ebpf:"kubearmor_events"`
	KubearmorExecPids          *ebpf.Map `ebpf:"kubearmor_exec_pids"`
	NsCgroupMap                *ebpf.Map `ebpf:"ns_cgroup_map"`
	NsFilterConfig             *ebpf.Map `ebpf:"ns_filter_config"`
	OngoingGrpcClientRequests  *ebpf.Map `ebpf:"ongoing_grpc_client_requests"`
	OngoingGrpcRequestStatus   *ebpf.Map `ebpf:"ongoing_grpc_request_status"`
	OngoingGrpcServerRequests  *ebpf.Map `ebpf:"ongoing_grpc_server_requests"`
	PortExclusionMap           *ebpf.Map `ebpf:"port_exclusion_map"`
	SslSymaddrs                *ebpf.Map `ebpf:"ssl_symaddrs"`
}

func (m *apiObserverMaps) Close() error {
	return _ApiObserverClose(
		m.ArgsBufk,
		m.Bufk,
		m.Bufs,
		m.BufsOff,
		m.CmdArgsBuf,
		m.GoH2ActiveEncoderMap,
		m.GoH2SingleHeaderEvents,
		m.GoH2SingleHeaderScratch,
		m.GoH2TransportEvents,
		m.GoH2TransportScratch,
		m.GoHttp2Events,
		m.GoOffsetsMap,
		m.GrpccEvents,
		m.GrpccSymaddrsMap,
		m.KaCgroupIds,
		m.KaExcludedCgroupIds,
		m.KaForkInfo,
		m.KaFoundPidEvents,
		m.KaPktHeap,
		m.KaPktHeapHash,
		m.KaPktId,
		m.KaPktsBuffer,
		m.KaSettings,
		m.KaSocketCgroups,
		m.KsAcceptSyscallContext,
		m.KsChunksBuffer,
		m.KsConnectSyscallInfo,
		m.KsConnectionContext,
		m.KsGoKernelReadContext,
		m.KsGoKernelWriteContext,
		m.KsGoReadContext,
		m.KsGoTlsFdOffsets,
		m.KsGoUserKernelReadContext,
		m.KsGoUserKernelWriteContext,
		m.KsGoWriteContext,
		m.KsHeap,
		m.KsOpensslConnAddr,
		m.KsOpensslReadContext,
		m.KsOpensslWriteContext,
		m.KsPidLastSocketFd,
		m.KsTgidLastSocketFd,
		m.KubearmorAlertThrottle,
		m.KubearmorArgsStore,
		m.KubearmorArguments,
		m.KubearmorConfig,
		m.KubearmorContainers,
		m.KubearmorEvents,
		m.KubearmorExecPids,
		m.NsCgroupMap,
		m.NsFilterConfig,
		m.OngoingGrpcClientRequests,
		m.OngoingGrpcRequestStatus,
		m.OngoingGrpcServerRequests,
		m.PortExclusionMap,
		m.SslSymaddrs,
	)
}

// apiObserverVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadApiObserverObjects or ebpf.CollectionSpec.LoadAndAssign.
type apiObserverVariables struct {
	KsInvalidFd *ebpf.Variable `ebpf:"ks_invalid_fd"`
}

// apiObserverPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadApiObserverObjects or ebpf.CollectionSpec.LoadAndAssign.
type apiObserverPrograms struct {
	KaFilterEgressPackets                  *ebpf.Program `ebpf:"ka_filter_egress_packets"`
	KaFilterIngressPackets                 *ebpf.Program `ebpf:"ka_filter_ingress_packets"`
	KaKretprobeSysExecve                   *ebpf.Program `ebpf:"ka_kretprobe_sys_execve"`
	KaSchedProcessFork                     *ebpf.Program `ebpf:"ka_sched_process_fork"`
	KaUprobeClientConnInvoke               *ebpf.Program `ebpf:"ka_uprobe_ClientConn_Invoke"`
	KaUprobeClientConnNewStream            *ebpf.Program `ebpf:"ka_uprobe_ClientConn_NewStream"`
	KaUprobeGoTlsRead                      *ebpf.Program `ebpf:"ka_uprobe_go_tls_read"`
	KaUprobeGoTlsReadEx                    *ebpf.Program `ebpf:"ka_uprobe_go_tls_read_ex"`
	KaUprobeGoTlsWrite                     *ebpf.Program `ebpf:"ka_uprobe_go_tls_write"`
	KaUprobeGoTlsWriteEx                   *ebpf.Program `ebpf:"ka_uprobe_go_tls_write_ex"`
	KaUprobeGrpcC_recvInitialMetadataEntry *ebpf.Program `ebpf:"ka_uprobe_grpc_c_recv_initial_metadata_entry"`
	KaUprobeHpackWriteField                *ebpf.Program `ebpf:"ka_uprobe_hpack_write_field"`
	KaUprobeHttp2WriteResHeaders           *ebpf.Program `ebpf:"ka_uprobe_http2_write_res_headers"`
	KaUprobeLoopyWriterWriteHeader         *ebpf.Program `ebpf:"ka_uprobe_loopy_writer_write_header"`
	KaUprobeNetHttpProcessHeaders          *ebpf.Program `ebpf:"ka_uprobe_net_http_processHeaders"`
	KaUprobeOperateHeadersClient           *ebpf.Program `ebpf:"ka_uprobe_operate_headers_client"`
	KaUprobeOperateHeadersClientEntry      *ebpf.Program `ebpf:"ka_uprobe_operate_headers_client_entry"`
	KaUprobeOperateHeadersServer           *ebpf.Program `ebpf:"ka_uprobe_operate_headers_server"`
	KaUprobeOperateHeadersServerEntry      *ebpf.Program `ebpf:"ka_uprobe_operate_headers_server_entry"`
	KaUprobeServerHandleStream             *ebpf.Program `ebpf:"ka_uprobe_server_handleStream"`
	KaUprobeTransportWriteStatus           *ebpf.Program `ebpf:"ka_uprobe_transport_writeStatus"`
	KaUretprobeClientConnInvoke            *ebpf.Program `ebpf:"ka_uretprobe_ClientConn_Invoke"`
	KaUretprobeClientStreamRecvMsg         *ebpf.Program `ebpf:"ka_uretprobe_clientStream_RecvMsg"`
	KaUretprobeServerHandleStream          *ebpf.Program `ebpf:"ka_uretprobe_server_handleStream"`
	KsKprobeTcpRecvmsg                     *ebpf.Program `ebpf:"ks_kprobe_tcp_recvmsg"`
	KsKprobeTcpSendmsg                     *ebpf.Program `ebpf:"ks_kprobe_tcp_sendmsg"`
	KsSslPending                           *ebpf.Program `ebpf:"ks_ssl_pending"`
	KsSslRead                              *ebpf.Program `ebpf:"ks_ssl_read"`
	KsSslReadEx                            *ebpf.Program `ebpf:"ks_ssl_read_ex"`
	KsSslRetRead                           *ebpf.Program `ebpf:"ks_ssl_ret_read"`
	KsSslRetReadEx                         *ebpf.Program `ebpf:"ks_ssl_ret_read_ex"`
	KsSslRetWrite                          *ebpf.Program `ebpf:"ks_ssl_ret_write"`
	KsSslRetWriteEx                        *ebpf.Program `ebpf:"ks_ssl_ret_write_ex"`
	KsSslWrite                             *ebpf.Program `ebpf:"ks_ssl_write"`
	KsSslWriteEx                           *ebpf.Program `ebpf:"ks_ssl_write_ex"`
	KsSysEnterAccept4                      *ebpf.Program `ebpf:"ks_sys_enter_accept4"`
	KsSysEnterConnect                      *ebpf.Program `ebpf:"ks_sys_enter_connect"`
	KsSysEnterRead                         *ebpf.Program `ebpf:"ks_sys_enter_read"`
	KsSysEnterReadv                        *ebpf.Program `ebpf:"ks_sys_enter_readv"`
	KsSysEnterRecvfrom                     *ebpf.Program `ebpf:"ks_sys_enter_recvfrom"`
	KsSysEnterRecvmsg                      *ebpf.Program `ebpf:"ks_sys_enter_recvmsg"`
	KsSysEnterSendmsg                      *ebpf.Program `ebpf:"ks_sys_enter_sendmsg"`
	KsSysEnterSendto                       *ebpf.Program `ebpf:"ks_sys_enter_sendto"`
	KsSysEnterWrite                        *ebpf.Program `ebpf:"ks_sys_enter_write"`
	KsSysEnterWritev                       *ebpf.Program `ebpf:"ks_sys_enter_writev"`
	KsSysExitAccept4                       *ebpf.Program `ebpf:"ks_sys_exit_accept4"`
	KsSysExitConnect                       *ebpf.Program `ebpf:"ks_sys_exit_connect"`
	KsSysExitRead                          *ebpf.Program `ebpf:"ks_sys_exit_read"`
	KsSysExitWrite                         *ebpf.Program `ebpf:"ks_sys_exit_write"`
}

func (p *apiObserverPrograms) Close() error {
	return _ApiObserverClose(
		p.KaFilterEgressPackets,
		p.KaFilterIngressPackets,
		p.KaKretprobeSysExecve,
		p.KaSchedProcessFork,
		p.KaUprobeClientConnInvoke,
		p.KaUprobeClientConnNewStream,
		p.KaUprobeGoTlsRead,
		p.KaUprobeGoTlsReadEx,
		p.KaUprobeGoTlsWrite,
		p.KaUprobeGoTlsWriteEx,
		p.KaUprobeGrpcC_recvInitialMetadataEntry,
		p.KaUprobeHpackWriteField,
		p.KaUprobeHttp2WriteResHeaders,
		p.KaUprobeLoopyWriterWriteHeader,
		p.KaUprobeNetHttpProcessHeaders,
		p.KaUprobeOperateHeadersClient,
		p.KaUprobeOperateHeadersClientEntry,
		p.KaUprobeOperateHeadersServer,
		p.KaUprobeOperateHeadersServerEntry,
		p.KaUprobeServerHandleStream,
		p.KaUprobeTransportWriteStatus,
		p.KaUretprobeClientConnInvoke,
		p.KaUretprobeClientStreamRecvMsg,
		p.KaUretprobeServerHandleStream,
		p.KsKprobeTcpRecvmsg,
		p.KsKprobeTcpSendmsg,
		p.KsSslPending,
		p.KsSslRead,
		p.KsSslReadEx,
		p.KsSslRetRead,
		p.KsSslRetReadEx,
		p.KsSslRetWrite,
		p.KsSslRetWriteEx,
		p.KsSslWrite,
		p.KsSslWriteEx,
		p.KsSysEnterAccept4,
		p.KsSysEnterConnect,
		p.KsSysEnterRead,
		p.KsSysEnterReadv,
		p.KsSysEnterRecvfrom,
		p.KsSysEnterRecvmsg,
		p.KsSysEnterSendmsg,
		p.KsSysEnterSendto,
		p.KsSysEnterWrite,
		p.KsSysEnterWritev,
		p.KsSysExitAccept4,
		p.KsSysExitConnect,
		p.KsSysExitRead,
		p.KsSysExitWrite,
	)
}

func _ApiObserverClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed apiobserver_arm64_bpfel.o
var _ApiObserverBytes []byte
