apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubearmor
  namespace: {{ .Values.namespace.name }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: controller-manager
  namespace: {{ .Values.namespace.name}}