//go:build !ignore_autogenerated

// SPDX-License-Identifier: Apache-2.0
// Copyright 2023 Authors of KubeArmor

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageSpec) DeepCopyInto(out *ImageSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageSpec.
func (in *ImageSpec) DeepCopy() *ImageSpec {
	if in == nil {
		return nil
	}
	out := new(ImageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeArmorConfig) DeepCopyInto(out *KubeArmorConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeArmorConfig.
func (in *KubeArmorConfig) DeepCopy() *KubeArmorConfig {
	if in == nil {
		return nil
	}
	out := new(KubeArmorConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KubeArmorConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeArmorConfigList) DeepCopyInto(out *KubeArmorConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KubeArmorConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeArmorConfigList.
func (in *KubeArmorConfigList) DeepCopy() *KubeArmorConfigList {
	if in == nil {
		return nil
	}
	out := new(KubeArmorConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KubeArmorConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeArmorConfigSpec) DeepCopyInto(out *KubeArmorConfigSpec) {
	*out = *in
	out.KubeArmorImage = in.KubeArmorImage
	out.KubeArmorInitImage = in.KubeArmorInitImage
	out.KubeArmorRelayImage = in.KubeArmorRelayImage
	out.KubeArmorControllerImage = in.KubeArmorControllerImage
	out.KubeRbacProxyImage = in.KubeRbacProxyImage
	in.Tls.DeepCopyInto(&out.Tls)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeArmorConfigSpec.
func (in *KubeArmorConfigSpec) DeepCopy() *KubeArmorConfigSpec {
	if in == nil {
		return nil
	}
	out := new(KubeArmorConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeArmorConfigStatus) DeepCopyInto(out *KubeArmorConfigStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeArmorConfigStatus.
func (in *KubeArmorConfigStatus) DeepCopy() *KubeArmorConfigStatus {
	if in == nil {
		return nil
	}
	out := new(KubeArmorConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Tls) DeepCopyInto(out *Tls) {
	*out = *in
	if in.RelayExtraDnsNames != nil {
		in, out := &in.RelayExtraDnsNames, &out.RelayExtraDnsNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RelayExtraIpAddresses != nil {
		in, out := &in.RelayExtraIpAddresses, &out.RelayExtraIpAddresses
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Tls.
func (in *Tls) DeepCopy() *Tls {
	if in == nil {
		return nil
	}
	out := new(Tls)
	in.DeepCopyInto(out)
	return out
}
