apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-group-2-file-path-block-from-source-path
  namespace: multiubuntu
spec:
  severity: 5
  message: "block /bin/cat from accessing /secret.txt"
  selector:
    matchLabels:
      group: group-2
  file:
    matchPaths:
      - path: /secret.txt # /bin/cat /secret.txt (permission denied)
        fromSource: # head /secret.txt (success)
        - path: /bin/cat
  action:
    Block
