// SPDX-License-Identifier: Apache-2.0
// Copyright 2023 Authors of KubeArmor

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	operatorkubearmorcomv1 "github.com/kubearmor/KubeArmor/pkg/KubeArmorOperator/api/operator.kubearmor.com/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeKubeArmorConfigs implements KubeArmorConfigInterface
type FakeKubeArmorConfigs struct {
	Fake *FakeOperatorV1
	ns   string
}

var kubearmorconfigsResource = schema.GroupVersionResource{Group: "operator.kubearmor.com", Version: "v1", Resource: "kubearmorconfigs"}

var kubearmorconfigsKind = schema.GroupVersionKind{Group: "operator.kubearmor.com", Version: "v1", Kind: "KubeArmorConfig"}

// Get takes name of the kubeArmorConfig, and returns the corresponding kubeArmorConfig object, and an error if there is any.
func (c *FakeKubeArmorConfigs) Get(ctx context.Context, name string, options v1.GetOptions) (result *operatorkubearmorcomv1.KubeArmorConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(kubearmorconfigsResource, c.ns, name), &operatorkubearmorcomv1.KubeArmorConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*operatorkubearmorcomv1.KubeArmorConfig), err
}

// List takes label and field selectors, and returns the list of KubeArmorConfigs that match those selectors.
func (c *FakeKubeArmorConfigs) List(ctx context.Context, opts v1.ListOptions) (result *operatorkubearmorcomv1.KubeArmorConfigList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(kubearmorconfigsResource, kubearmorconfigsKind, c.ns, opts), &operatorkubearmorcomv1.KubeArmorConfigList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &operatorkubearmorcomv1.KubeArmorConfigList{ListMeta: obj.(*operatorkubearmorcomv1.KubeArmorConfigList).ListMeta}
	for _, item := range obj.(*operatorkubearmorcomv1.KubeArmorConfigList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested kubeArmorConfigs.
func (c *FakeKubeArmorConfigs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(kubearmorconfigsResource, c.ns, opts))

}

// Create takes the representation of a kubeArmorConfig and creates it.  Returns the server's representation of the kubeArmorConfig, and an error, if there is any.
func (c *FakeKubeArmorConfigs) Create(ctx context.Context, kubeArmorConfig *operatorkubearmorcomv1.KubeArmorConfig, opts v1.CreateOptions) (result *operatorkubearmorcomv1.KubeArmorConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(kubearmorconfigsResource, c.ns, kubeArmorConfig), &operatorkubearmorcomv1.KubeArmorConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*operatorkubearmorcomv1.KubeArmorConfig), err
}

// Update takes the representation of a kubeArmorConfig and updates it. Returns the server's representation of the kubeArmorConfig, and an error, if there is any.
func (c *FakeKubeArmorConfigs) Update(ctx context.Context, kubeArmorConfig *operatorkubearmorcomv1.KubeArmorConfig, opts v1.UpdateOptions) (result *operatorkubearmorcomv1.KubeArmorConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(kubearmorconfigsResource, c.ns, kubeArmorConfig), &operatorkubearmorcomv1.KubeArmorConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*operatorkubearmorcomv1.KubeArmorConfig), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeKubeArmorConfigs) UpdateStatus(ctx context.Context, kubeArmorConfig *operatorkubearmorcomv1.KubeArmorConfig, opts v1.UpdateOptions) (*operatorkubearmorcomv1.KubeArmorConfig, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(kubearmorconfigsResource, "status", c.ns, kubeArmorConfig), &operatorkubearmorcomv1.KubeArmorConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*operatorkubearmorcomv1.KubeArmorConfig), err
}

// Delete takes name of the kubeArmorConfig and deletes it. Returns an error if one occurs.
func (c *FakeKubeArmorConfigs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(kubearmorconfigsResource, c.ns, name), &operatorkubearmorcomv1.KubeArmorConfig{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeKubeArmorConfigs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(kubearmorconfigsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &operatorkubearmorcomv1.KubeArmorConfigList{})
	return err
}

// Patch applies the patch and returns the patched kubeArmorConfig.
func (c *FakeKubeArmorConfigs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *operatorkubearmorcomv1.KubeArmorConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(kubearmorconfigsResource, c.ns, name, pt, data, subresources...), &operatorkubearmorcomv1.KubeArmorConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*operatorkubearmorcomv1.KubeArmorConfig), err
}
