// SPDX-License-Identifier: Apache-2.0
// Copyright 2023 Authors of KubeArmor

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/kubearmor/KubeArmor/pkg/KubeArmorOperator/client/clientset/versioned/typed/operator.kubearmor.com/v1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeOperatorV1 struct {
	*testing.Fake
}

func (c *FakeOperatorV1) KubeArmorConfigs(namespace string) v1.KubeArmorConfigInterface {
	return &FakeKubeArmorConfigs{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeOperatorV1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
