// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Authors of KubeArmor

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	securitykubearmorcomv1 "github.com/kubearmor/KubeArmor/pkg/KubeArmorController/api/security.kubearmor.com/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeKubeArmorNetworkPolicies implements KubeArmorNetworkPolicyInterface
type FakeKubeArmorNetworkPolicies struct {
	Fake *FakeSecurityV1
}

var kubearmornetworkpoliciesResource = schema.GroupVersionResource{Group: "security.kubearmor.com", Version: "v1", Resource: "kubearmornetworkpolicies"}

var kubearmornetworkpoliciesKind = schema.GroupVersionKind{Group: "security.kubearmor.com", Version: "v1", Kind: "KubeArmorNetworkPolicy"}

// Get takes name of the kubeArmorNetworkPolicy, and returns the corresponding kubeArmorNetworkPolicy object, and an error if there is any.
func (c *FakeKubeArmorNetworkPolicies) Get(ctx context.Context, name string, options v1.GetOptions) (result *securitykubearmorcomv1.KubeArmorNetworkPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(kubearmornetworkpoliciesResource, name), &securitykubearmorcomv1.KubeArmorNetworkPolicy{})
	if obj == nil {
		return nil, err
	}
	return obj.(*securitykubearmorcomv1.KubeArmorNetworkPolicy), err
}

// List takes label and field selectors, and returns the list of KubeArmorNetworkPolicies that match those selectors.
func (c *FakeKubeArmorNetworkPolicies) List(ctx context.Context, opts v1.ListOptions) (result *securitykubearmorcomv1.KubeArmorNetworkPolicyList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(kubearmornetworkpoliciesResource, kubearmornetworkpoliciesKind, opts), &securitykubearmorcomv1.KubeArmorNetworkPolicyList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &securitykubearmorcomv1.KubeArmorNetworkPolicyList{ListMeta: obj.(*securitykubearmorcomv1.KubeArmorNetworkPolicyList).ListMeta}
	for _, item := range obj.(*securitykubearmorcomv1.KubeArmorNetworkPolicyList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested kubeArmorNetworkPolicies.
func (c *FakeKubeArmorNetworkPolicies) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(kubearmornetworkpoliciesResource, opts))
}

// Create takes the representation of a kubeArmorNetworkPolicy and creates it.  Returns the server's representation of the kubeArmorNetworkPolicy, and an error, if there is any.
func (c *FakeKubeArmorNetworkPolicies) Create(ctx context.Context, kubeArmorNetworkPolicy *securitykubearmorcomv1.KubeArmorNetworkPolicy, opts v1.CreateOptions) (result *securitykubearmorcomv1.KubeArmorNetworkPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(kubearmornetworkpoliciesResource, kubeArmorNetworkPolicy), &securitykubearmorcomv1.KubeArmorNetworkPolicy{})
	if obj == nil {
		return nil, err
	}
	return obj.(*securitykubearmorcomv1.KubeArmorNetworkPolicy), err
}

// Update takes the representation of a kubeArmorNetworkPolicy and updates it. Returns the server's representation of the kubeArmorNetworkPolicy, and an error, if there is any.
func (c *FakeKubeArmorNetworkPolicies) Update(ctx context.Context, kubeArmorNetworkPolicy *securitykubearmorcomv1.KubeArmorNetworkPolicy, opts v1.UpdateOptions) (result *securitykubearmorcomv1.KubeArmorNetworkPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(kubearmornetworkpoliciesResource, kubeArmorNetworkPolicy), &securitykubearmorcomv1.KubeArmorNetworkPolicy{})
	if obj == nil {
		return nil, err
	}
	return obj.(*securitykubearmorcomv1.KubeArmorNetworkPolicy), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeKubeArmorNetworkPolicies) UpdateStatus(ctx context.Context, kubeArmorNetworkPolicy *securitykubearmorcomv1.KubeArmorNetworkPolicy, opts v1.UpdateOptions) (*securitykubearmorcomv1.KubeArmorNetworkPolicy, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(kubearmornetworkpoliciesResource, "status", kubeArmorNetworkPolicy), &securitykubearmorcomv1.KubeArmorNetworkPolicy{})
	if obj == nil {
		return nil, err
	}
	return obj.(*securitykubearmorcomv1.KubeArmorNetworkPolicy), err
}

// Delete takes name of the kubeArmorNetworkPolicy and deletes it. Returns an error if one occurs.
func (c *FakeKubeArmorNetworkPolicies) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(kubearmornetworkpoliciesResource, name), &securitykubearmorcomv1.KubeArmorNetworkPolicy{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeKubeArmorNetworkPolicies) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(kubearmornetworkpoliciesResource, listOpts)

	_, err := c.Fake.Invokes(action, &securitykubearmorcomv1.KubeArmorNetworkPolicyList{})
	return err
}

// Patch applies the patch and returns the patched kubeArmorNetworkPolicy.
func (c *FakeKubeArmorNetworkPolicies) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *securitykubearmorcomv1.KubeArmorNetworkPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(kubearmornetworkpoliciesResource, name, pt, data, subresources...), &securitykubearmorcomv1.KubeArmorNetworkPolicy{})
	if obj == nil {
		return nil, err
	}
	return obj.(*securitykubearmorcomv1.KubeArmorNetworkPolicy), err
}
