apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.kubearmorOperator.name }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.snitch.name }}
  namespace: {{ .Release.Namespace }}

