---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.kubearmorOperator.name }}-webhook-service
  namespace: {{.Release.Namespace}}
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 9443
  selector:
    kubearmor-app: {{ .Values.kubearmorOperator.name }}