// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Authors of KubeArmor

// Code generated by lister-gen. DO NOT EDIT.

package v1

// KubeArmorClusterPolicyListerExpansion allows custom methods to be added to
// KubeArmorClusterPolicyLister.
type KubeArmorClusterPolicyListerExpansion interface{}

// KubeArmorHostPolicyListerExpansion allows custom methods to be added to
// KubeArmorHostPolicyLister.
type KubeArmorHostPolicyListerExpansion interface{}

// KubeArmorPolicyListerExpansion allows custom methods to be added to
// KubeArmorPolicyLister.
type KubeArmorPolicyListerExpansion interface{}

// KubeArmorPolicyNamespaceListerExpansion allows custom methods to be added to
// KubeArmorPolicyNamespaceLister.
type KubeArmorPolicyNamespaceListerExpansion interface{}
