// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Authors of KubeArmor

// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/kubearmor/KubeArmor/pkg/KubeArmorController/api/security.kubearmor.com/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// KubeArmorNetworkPolicyLister helps list KubeArmorNetworkPolicies.
// All objects returned here must be treated as read-only.
type KubeArmorNetworkPolicyLister interface {
	// List lists all KubeArmorNetworkPolicies in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1.KubeArmorNetworkPolicy, err error)
	// Get retrieves the KubeArmorNetworkPolicy from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1.KubeArmorNetworkPolicy, error)
	KubeArmorNetworkPolicyListerExpansion
}

// kubeArmorNetworkPolicyLister implements the KubeArmorNetworkPolicyLister interface.
type kubeArmorNetworkPolicyLister struct {
	indexer cache.Indexer
}

// NewKubeArmorNetworkPolicyLister returns a new KubeArmorNetworkPolicyLister.
func NewKubeArmorNetworkPolicyLister(indexer cache.Indexer) KubeArmorNetworkPolicyLister {
	return &kubeArmorNetworkPolicyLister{indexer: indexer}
}

// List lists all KubeArmorNetworkPolicies in the indexer.
func (s *kubeArmorNetworkPolicyLister) List(selector labels.Selector) (ret []*v1.KubeArmorNetworkPolicy, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.KubeArmorNetworkPolicy))
	})
	return ret, err
}

// Get retrieves the KubeArmorNetworkPolicy from the index for a given name.
func (s *kubeArmorNetworkPolicyLister) Get(name string) (*v1.KubeArmorNetworkPolicy, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1.Resource("kubearmornetworkpolicy"), name)
	}
	return obj.(*v1.KubeArmorNetworkPolicy), nil
}
