// SPDX-License-Identifier: Apache-2.0
// Copyright 2023 Authors of KubeArmor

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	"context"
	time "time"

	operatorkubearmorcomv1 "github.com/kubearmor/KubeArmor/pkg/KubeArmorOperator/api/operator.kubearmor.com/v1"
	versioned "github.com/kubearmor/KubeArmor/pkg/KubeArmorOperator/client/clientset/versioned"
	internalinterfaces "github.com/kubearmor/KubeArmor/pkg/KubeArmorOperator/client/informers/externalversions/internalinterfaces"
	v1 "github.com/kubearmor/KubeArmor/pkg/KubeArmorOperator/client/listers/operator.kubearmor.com/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// KubeArmorConfigInformer provides access to a shared informer and lister for
// KubeArmorConfigs.
type KubeArmorConfigInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.KubeArmorConfigLister
}

type kubeArmorConfigInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewKubeArmorConfigInformer constructs a new informer for KubeArmorConfig type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewKubeArmorConfigInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredKubeArmorConfigInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredKubeArmorConfigInformer constructs a new informer for KubeArmorConfig type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredKubeArmorConfigInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.OperatorV1().KubeArmorConfigs(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.OperatorV1().KubeArmorConfigs(namespace).Watch(context.TODO(), options)
			},
		},
		&operatorkubearmorcomv1.KubeArmorConfig{},
		resyncPeriod,
		indexers,
	)
}

func (f *kubeArmorConfigInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredKubeArmorConfigInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *kubeArmorConfigInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&operatorkubearmorcomv1.KubeArmorConfig{}, f.defaultInformer)
}

func (f *kubeArmorConfigInformer) Lister() v1.KubeArmorConfigLister {
	return v1.NewKubeArmorConfigLister(f.Informer().GetIndexer())
}
