// SPDX-License-Identifier: Apache-2.0
// Copyright 2021 Authors of KubeArmor

// Code generated by lister-gen. DO NOT EDIT.

package v1

// KubeArmorPolicyListerExpansion allows custom methods to be added to
// KubeArmorPolicyLister.
type KubeArmorPolicyListerExpansion interface{}

// KubeArmorPolicyNamespaceListerExpansion allows custom methods to be added to
// KubeArmorPolicyNamespaceLister.
type KubeArmorPolicyNamespaceListerExpansion interface{}
