apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubearmor-mysql-client
  labels:
    kubearmor-app: kubearmor-mysql-client
spec:
  replicas: 1
  selector:
    matchLabels:
      kubearmor-app: kubearmor-mysql-client
  template:
    metadata:
      labels:
        kubearmor-app: kubearmor-mysql-client
      annotations:
        kubearmor-policy: audited
    spec:
      containers:
      - name: kubearmor-mysql-client
        image: accuknox/kubearmor-mysql-client:latest
        env:
        - name: KUBEARMOR_SERVICE
          value: kubearmor.kube-system.svc:32767
        - name: DB_HOST
          value: kubearmor-mysql:3306
        - name: DB_NAME
          value: kubearmor-db
        - name: DB_USER
          value: kubearmor
        - name: DB_PASSWD
          value: kubearmor-passwd
        - name: TABLE_MSG
          value: messages
        - name: TABLE_ALERT
          value: alerts
        - name: TABLE_LOG
          value: syslogs
