apiVersion: security.kubearmor.com/v1
kind: KubeArmorClusterPolicy
metadata:
  annotations:
    app.accuknox.com/source: KubeArmor Operator
    app.accuknox.com/type: harden
  name: harden-write-in-shm-dir
  namespace: gmp-system
spec:
  action: Audit
  file:
    matchDirectories:
    - dir: /dev/shm/
      readOnly: true
      recursive: true
  message: Alert! write to /dev/shm folder prevented.
  selector:
    matchExpressions:
  severity: 5
  tags:
  - MITRE
  - MITRE_TA0002_Execution

