apiVersion: security.kubearmor.com/v1
kind: KubeArmorClusterPolicy
metadata:
  annotations:
    app.accuknox.com/source: KubeArmor Operator
    app.accuknox.com/type: harden
  name: harden-cronjob-cfg
spec:
  action: Audit
  file:
    matchDirectories:
    - dir: /etc/cron.d/
      recursive: true
    - dir: /etc/cron.daily/
      recursive: true
    - dir: /etc/cron.hourly/
      recursive: true
    - dir: /etc/cron.monthly/
      recursive: true
    - dir: /etc/cron.weekly/
      recursive: true
    - dir: /var/cron/
      recursive: true
    - dir: /var/spool/cron/
      recursive: true
    matchPaths:
    - path: /etc/crontab
  message: Alert! Access to cron job files/directories detected.
  selector:
    matchExpressions:
  severity: 5
  tags:
  - CIS
  - CIS_5.1_Configure_Cron
  - CIS_Linux
  - NIST
  - NIST_800-53_SI-4
  - SI-4

