// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package bpflsm

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type args_monitorArgBufsK struct {
	_    structs.HostLayout
	Okey struct {
		_     structs.HostLayout
		PidNs uint32
		MntNs uint32
	}
	Store args_monitorBufsK
	Arg   [104]int8
}

type args_monitorArgVal struct {
	_         structs.HostLayout
	ArgsArray [104]int8
}

type args_monitorBufsK struct {
	_      structs.HostLayout
	Path   [200]int8
	Source [200]int8
}

type args_monitorBufsT struct {
	_   structs.HostLayout
	Buf [32768]int8
}

type args_monitorCmdArgsKey struct {
	_    structs.HostLayout
	Tgid uint64
	Ind  uint64
}

// loadArgs_monitor returns the embedded CollectionSpec for args_monitor.
func loadArgs_monitor() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_Args_monitorBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load args_monitor: %w", err)
	}

	return spec, err
}

// loadArgs_monitorObjects loads args_monitor and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*args_monitorObjects
//	*args_monitorPrograms
//	*args_monitorMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadArgs_monitorObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadArgs_monitor()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// args_monitorSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type args_monitorSpecs struct {
	args_monitorProgramSpecs
	args_monitorMapSpecs
	args_monitorVariableSpecs
}

// args_monitorProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type args_monitorProgramSpecs struct {
	KprobeArgsExecve *ebpf.ProgramSpec `ebpf:"kprobe__args_execve"`
}

// args_monitorMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type args_monitorMapSpecs struct {
	ArgsBufk               *ebpf.MapSpec `ebpf:"args_bufk"`
	Bufk                   *ebpf.MapSpec `ebpf:"bufk"`
	Bufs                   *ebpf.MapSpec `ebpf:"bufs"`
	BufsOff                *ebpf.MapSpec `ebpf:"bufs_off"`
	CmdArgsBuf             *ebpf.MapSpec `ebpf:"cmd_args_buf"`
	KubearmorAlertThrottle *ebpf.MapSpec `ebpf:"kubearmor_alert_throttle"`
	KubearmorArgsStore     *ebpf.MapSpec `ebpf:"kubearmor_args_store"`
	KubearmorArguments     *ebpf.MapSpec `ebpf:"kubearmor_arguments"`
	KubearmorConfig        *ebpf.MapSpec `ebpf:"kubearmor_config"`
	KubearmorContainers    *ebpf.MapSpec `ebpf:"kubearmor_containers"`
	KubearmorEvents        *ebpf.MapSpec `ebpf:"kubearmor_events"`
	KubearmorExecPids      *ebpf.MapSpec `ebpf:"kubearmor_exec_pids"`
}

// args_monitorVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type args_monitorVariableSpecs struct {
}

// args_monitorObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadArgs_monitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type args_monitorObjects struct {
	args_monitorPrograms
	args_monitorMaps
	args_monitorVariables
}

func (o *args_monitorObjects) Close() error {
	return _Args_monitorClose(
		&o.args_monitorPrograms,
		&o.args_monitorMaps,
	)
}

// args_monitorMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadArgs_monitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type args_monitorMaps struct {
	ArgsBufk               *ebpf.Map `ebpf:"args_bufk"`
	Bufk                   *ebpf.Map `ebpf:"bufk"`
	Bufs                   *ebpf.Map `ebpf:"bufs"`
	BufsOff                *ebpf.Map `ebpf:"bufs_off"`
	CmdArgsBuf             *ebpf.Map `ebpf:"cmd_args_buf"`
	KubearmorAlertThrottle *ebpf.Map `ebpf:"kubearmor_alert_throttle"`
	KubearmorArgsStore     *ebpf.Map `ebpf:"kubearmor_args_store"`
	KubearmorArguments     *ebpf.Map `ebpf:"kubearmor_arguments"`
	KubearmorConfig        *ebpf.Map `ebpf:"kubearmor_config"`
	KubearmorContainers    *ebpf.Map `ebpf:"kubearmor_containers"`
	KubearmorEvents        *ebpf.Map `ebpf:"kubearmor_events"`
	KubearmorExecPids      *ebpf.Map `ebpf:"kubearmor_exec_pids"`
}

func (m *args_monitorMaps) Close() error {
	return _Args_monitorClose(
		m.ArgsBufk,
		m.Bufk,
		m.Bufs,
		m.BufsOff,
		m.CmdArgsBuf,
		m.KubearmorAlertThrottle,
		m.KubearmorArgsStore,
		m.KubearmorArguments,
		m.KubearmorConfig,
		m.KubearmorContainers,
		m.KubearmorEvents,
		m.KubearmorExecPids,
	)
}

// args_monitorVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadArgs_monitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type args_monitorVariables struct {
}

// args_monitorPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadArgs_monitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type args_monitorPrograms struct {
	KprobeArgsExecve *ebpf.Program `ebpf:"kprobe__args_execve"`
}

func (p *args_monitorPrograms) Close() error {
	return _Args_monitorClose(
		p.KprobeArgsExecve,
	)
}

func _Args_monitorClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed args_monitor_bpfel.o
var _Args_monitorBytes []byte
