// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package bpflsm

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type process_monitorArgBufsK struct {
	_     structs.HostLayout
	Okey  process_monitorOuterKey
	Store process_monitorBufsK
	Arg   [104]int8
}

type process_monitorArgVal struct {
	_         structs.HostLayout
	ArgsArray [104]int8
}

type process_monitorBufsK struct {
	_      structs.HostLayout
	Path   [200]int8
	Source [200]int8
}

type process_monitorBufsT struct {
	_   structs.HostLayout
	Buf [32768]int8
}

type process_monitorCmdArgsKey struct {
	_    structs.HostLayout
	Tgid uint64
	Ind  uint64
}

type process_monitorOuterKey struct {
	_     structs.HostLayout
	PidNs uint32
	MntNs uint32
}

// loadProcess_monitor returns the embedded CollectionSpec for process_monitor.
func loadProcess_monitor() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_Process_monitorBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load process_monitor: %w", err)
	}

	return spec, err
}

// loadProcess_monitorObjects loads process_monitor and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*process_monitorObjects
//	*process_monitorPrograms
//	*process_monitorMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadProcess_monitorObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadProcess_monitor()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// process_monitorSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type process_monitorSpecs struct {
	process_monitorProgramSpecs
	process_monitorMapSpecs
	process_monitorVariableSpecs
}

// process_monitorProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type process_monitorProgramSpecs struct {
	KprobeArgsExecve *ebpf.ProgramSpec `ebpf:"kprobe__args_execve"`
	SchedProcessExit *ebpf.ProgramSpec `ebpf:"sched_process_exit"`
	SchedProcessFork *ebpf.ProgramSpec `ebpf:"sched_process_fork"`
	SysEnterSetns    *ebpf.ProgramSpec `ebpf:"sys_enter_setns"`
	SysExitSetns     *ebpf.ProgramSpec `ebpf:"sys_exit_setns"`
}

// process_monitorMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type process_monitorMapSpecs struct {
	ArgsBufk               *ebpf.MapSpec `ebpf:"args_bufk"`
	Bufk                   *ebpf.MapSpec `ebpf:"bufk"`
	Bufs                   *ebpf.MapSpec `ebpf:"bufs"`
	BufsOff                *ebpf.MapSpec `ebpf:"bufs_off"`
	CmdArgsBuf             *ebpf.MapSpec `ebpf:"cmd_args_buf"`
	KubearmorAlertThrottle *ebpf.MapSpec `ebpf:"kubearmor_alert_throttle"`
	KubearmorArgsStore     *ebpf.MapSpec `ebpf:"kubearmor_args_store"`
	KubearmorArguments     *ebpf.MapSpec `ebpf:"kubearmor_arguments"`
	KubearmorConfig        *ebpf.MapSpec `ebpf:"kubearmor_config"`
	KubearmorContainers    *ebpf.MapSpec `ebpf:"kubearmor_containers"`
	KubearmorEvents        *ebpf.MapSpec `ebpf:"kubearmor_events"`
	KubearmorExecPids      *ebpf.MapSpec `ebpf:"kubearmor_exec_pids"`
	NsTransition           *ebpf.MapSpec `ebpf:"ns_transition"`
}

// process_monitorVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type process_monitorVariableSpecs struct {
}

// process_monitorObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadProcess_monitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type process_monitorObjects struct {
	process_monitorPrograms
	process_monitorMaps
	process_monitorVariables
}

func (o *process_monitorObjects) Close() error {
	return _Process_monitorClose(
		&o.process_monitorPrograms,
		&o.process_monitorMaps,
	)
}

// process_monitorMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadProcess_monitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type process_monitorMaps struct {
	ArgsBufk               *ebpf.Map `ebpf:"args_bufk"`
	Bufk                   *ebpf.Map `ebpf:"bufk"`
	Bufs                   *ebpf.Map `ebpf:"bufs"`
	BufsOff                *ebpf.Map `ebpf:"bufs_off"`
	CmdArgsBuf             *ebpf.Map `ebpf:"cmd_args_buf"`
	KubearmorAlertThrottle *ebpf.Map `ebpf:"kubearmor_alert_throttle"`
	KubearmorArgsStore     *ebpf.Map `ebpf:"kubearmor_args_store"`
	KubearmorArguments     *ebpf.Map `ebpf:"kubearmor_arguments"`
	KubearmorConfig        *ebpf.Map `ebpf:"kubearmor_config"`
	KubearmorContainers    *ebpf.Map `ebpf:"kubearmor_containers"`
	KubearmorEvents        *ebpf.Map `ebpf:"kubearmor_events"`
	KubearmorExecPids      *ebpf.Map `ebpf:"kubearmor_exec_pids"`
	NsTransition           *ebpf.Map `ebpf:"ns_transition"`
}

func (m *process_monitorMaps) Close() error {
	return _Process_monitorClose(
		m.ArgsBufk,
		m.Bufk,
		m.Bufs,
		m.BufsOff,
		m.CmdArgsBuf,
		m.KubearmorAlertThrottle,
		m.KubearmorArgsStore,
		m.KubearmorArguments,
		m.KubearmorConfig,
		m.KubearmorContainers,
		m.KubearmorEvents,
		m.KubearmorExecPids,
		m.NsTransition,
	)
}

// process_monitorVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadProcess_monitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type process_monitorVariables struct {
}

// process_monitorPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadProcess_monitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type process_monitorPrograms struct {
	KprobeArgsExecve *ebpf.Program `ebpf:"kprobe__args_execve"`
	SchedProcessExit *ebpf.Program `ebpf:"sched_process_exit"`
	SchedProcessFork *ebpf.Program `ebpf:"sched_process_fork"`
	SysEnterSetns    *ebpf.Program `ebpf:"sys_enter_setns"`
	SysExitSetns     *ebpf.Program `ebpf:"sys_exit_setns"`
}

func (p *process_monitorPrograms) Close() error {
	return _Process_monitorClose(
		p.KprobeArgsExecve,
		p.SchedProcessExit,
		p.SchedProcessFork,
		p.SysEnterSetns,
		p.SysExitSetns,
	)
}

func _Process_monitorClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed process_monitor_bpfeb.o
var _Process_monitorBytes []byte
