// SPDX-License-Identifier: Apache-2.0
// Copyright 2021 Authors of KubeArmor

package crd

import (
	_ "embed"
	"log"

	"sigs.k8s.io/yaml"

	apiextensionsv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
)

//go:embed KubeArmorPolicy.yaml
var crdBytes []byte

// GetCRD returns the generated CRD. The CRD is generated by controller-gen
// which is embedded at compile time using go:embed.
func GetCRD() apiextensionsv1.CustomResourceDefinition {
	ksp := apiextensionsv1.CustomResourceDefinition{}
	err := yaml.Unmarshal(crdBytes, &ksp)
	if err != nil {
		log.Fatal("Error unmarshalling pregenerated CRD")
	}
	return ksp
}
