## Append samples of your project ##
resources:
- operator_v1_kubearmorconfig.yaml
- security_v1_kubearmorpolicy.yaml
- security_v1_kubearmorhostpolicy.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
