# kubearmor-ca secret (observability plane)
{{- $ca := genCA "kubearmor"  1095 -}}
{{- if .Values.tls.enabled }}
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ .Values.kubearmor.tls.caSecretName }}
  labels:
    kubearmor-app: {{ .Values.kubearmor.tls.caSecretName }}
  namespace: {{.Release.Namespace}}
data:
  tls.key: {{ $ca.Key | b64enc }}
  tls.crt: {{ $ca.Cert | b64enc }}
{{- end}}
---
# kubearmor-management-ca secret (management plane)
{{- $mgmtCa := genCA "kubearmor-management" 1095 -}}
{{- if .Values.tls.enabled }}
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ .Values.kubearmor.tls.managementCaSecretName }}
  labels:
    kubearmor-app: {{ .Values.kubearmor.tls.managementCaSecretName }}
  namespace: {{.Release.Namespace}}
data:
  tls.key: {{ $mgmtCa.Key | b64enc }}
  tls.crt: {{ $mgmtCa.Cert | b64enc }}
{{- end}}
---
{{- if .Values.tls.enabled }}
{{- $altNames := list ( printf "kubearmor.%s" .Release.Namespace ) ( printf "kubearmor.%s.svc" .Release.Namespace ) ( printf "kubearmor.%s.svc.cluster.local" .Release.Namespace ) -}}
{{- $dns := concat .Values.kubearmorRelay.tls.extraDnsNames $altNames -}}
{{- $ip := .Values.kubearmorRelay.tls.extraIpAddresses -}}
{{- $cert := genSignedCert "kubearmor-relay" $ip $dns 1095 $ca -}}
# kubearmor-relay-certs secret
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ .Values.kubearmorRelay.tls.certSecretName }}
  labels:
    kubearmor-app: {{ .Values.kubearmorRelay.tls.certSecretName }}
  namespace: {{.Release.Namespace}}
data:
  tls.key: {{ $cert.Key | b64enc }}
  tls.crt: {{ $cert.Cert | b64enc }}
  ca.crt: {{ $ca.Cert | b64enc }}
{{- end}}
---
{{- if .Values.tls.enabled }}
{{- $cert := genSignedCert "kubearmor-relay" nil nil 1095 $ca -}}
# kubearmor-client-certs secret
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ .Values.kubearmor.tls.clientCertSecretName }}
  labels:
    kubearmor-app: {{ .Values.kubearmor.tls.clientCertSecretName }}
  namespace: {{.Release.Namespace}}
data:
  tls.key: {{ $cert.Key | b64enc }}
  tls.crt: {{ $cert.Cert | b64enc }}
  ca.crt: {{ $ca.Cert | b64enc }}
{{- end}}
---
{{- if .Values.tls.enabled }}
{{- $mgmtAltNames := list ( printf "kubearmor-management.%s" .Release.Namespace ) ( printf "kubearmor-management.%s.svc" .Release.Namespace ) ( printf "kubearmor-management.%s.svc.cluster.local" .Release.Namespace ) -}}
{{- $mgmtDns := concat .Values.kubearmor.tls.managementExtraDnsNames $mgmtAltNames -}}
{{- $mgmtIp := .Values.kubearmor.tls.managementExtraIpAddresses -}}
{{- $mgmtCert := genSignedCert "kubearmor-management-server" $mgmtIp $mgmtDns 1095 $mgmtCa -}}
# kubearmor-management-server-certs secret
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ .Values.kubearmor.tls.managementCertSecretName }}
  labels:
    kubearmor-app: {{ .Values.kubearmor.tls.managementCertSecretName }}
  namespace: {{.Release.Namespace}}
data:
  tls.key: {{ $mgmtCert.Key | b64enc }}
  tls.crt: {{ $mgmtCert.Cert | b64enc }}
  ca.crt: {{ $mgmtCa.Cert | b64enc }}
{{- end}}
---
{{- if .Values.tls.enabled }}
{{- $mgmtClientCert := genSignedCert "kubearmor-management-client" nil nil 1095 $mgmtCa -}}
# kubearmor-management-client-certs secret
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ .Values.kubearmor.tls.managementClientCertSecretName }}
  labels:
    kubearmor-app: {{ .Values.kubearmor.tls.managementClientCertSecretName }}
  namespace: {{.Release.Namespace}}
data:
  tls.key: {{ $mgmtClientCert.Key | b64enc }}
  tls.crt: {{ $mgmtClientCert.Cert | b64enc }}
  ca.crt: {{ $mgmtCa.Cert | b64enc }}
{{- end}}