apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubearmor
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    kubearmor-app: {{ .Values.kubearmorController.name }}-service-account
  name: {{ .Values.kubearmorController.name }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubearmor-relay
  namespace: {{ .Release.Namespace }}