//**********************************************************************`
//* This is an include file generated by Message Compiler.             *`
//*                                                                    *`
//* Copyright (c) Microsoft Corporation. All Rights Reserved.          *`
//**********************************************************************`
#pragma once

//+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
// Provider "KarmorProvider" event count 2
//+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

// Provider GUID = 12345678-1234-1234-1234-123456789012
EXTERN_C __declspec(selectany) const GUID KarmorProvider = {0x12345678, 0x1234, 0x1234, {0x12, 0x34, 0x12, 0x34, 0x56, 0x78, 0x90, 0x12}};

#ifndef KarmorProvider_Traits
#define KarmorProvider_Traits NULL
#endif // KarmorProvider_Traits

//
// Channel
//
#define KarmorProvider_CHANNEL_System 0x8

//
// Opcodes
//
#define BlockOpcode 0xa
#define AuditOpcode 0xb

//
// Tasks
//
#define ProcessControlTask 0x1

//
// Event Descriptors
//
EXTERN_C __declspec(selectany) const EVENT_DESCRIPTOR ProcessBlocked = {0x1, 0x0, 0x8, 0x3, 0xa, 0x1, 0x0};
#define ProcessBlocked_value 0x1
EXTERN_C __declspec(selectany) const EVENT_DESCRIPTOR ProcessAudited = {0x2, 0x0, 0x8, 0x4, 0xb, 0x1, 0x0};
#define ProcessAudited_value 0x2

#define MSG_ProcessBlocked_EventMessage      0x00000001L
#define MSG_ProcessAudited_EventMessage      0x00000002L
