// SPDX-License-Identifier: Apache-2.0
// Copyright 2023 Authors of KubeArmor

// Code generated by lister-gen. DO NOT EDIT.

package v1

// KubeArmorConfigListerExpansion allows custom methods to be added to
// KubeArmorConfigLister.
type KubeArmorConfigListerExpansion interface{}

// KubeArmorConfigNamespaceListerExpansion allows custom methods to be added to
// KubeArmorConfigNamespaceLister.
type KubeArmorConfigNamespaceListerExpansion interface{}
