kubearmorOperator:
  name: kubearmor-operator
  image:
    repository: kubearmor/kubearmor-operator
    tag: latest
  imagePullPolicy: IfNotPresent
  serviceAccount:
    annotations: {}
kubernetesClusterDomain: cluster.local
