apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.kubearmorOperator.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    kubearmor-app: {{ .Values.kubearmorOperator.name }}
spec:
  selector:
    matchLabels:
      kubearmor-app: {{ .Values.kubearmorOperator.name }}
  template:
    metadata:
      labels:
        kubearmor-app: {{ .Values.kubearmorOperator.name }}
    spec:
      containers:
      - command:
        - /operator
        - kubearmor-operator
        env:
        - name: KUBEARMOR_OPERATOR_NS
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ printf "%s:%s" .Values.kubearmorOperator.image.repository .Values.kubearmorOperator.image.tag}}
        imagePullPolicy: {{ .Values.kubearmorOperator.imagePullPolicy }}
        name: {{ .Values.kubearmorOperator.name }}
      serviceAccountName: {{ .Values.kubearmorOperator.name }}