project_name: kubearmor

builds:
  - binary: "opt/kubearmor/kubearmor"
    id: kubearmor
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - "-X main.BuildDate={{.Date}}"
      - "-X main.GitCommit={{.Commit}}"
      - "-X main.GitBranch={{.Branch}}"
      - "-X main.GitSummary={{.Summary}}"

release:
  replace_existing_artifacts: true
  mode: replace
  make_latest: false

signs:
  - cmd: cosign
    certificate: '${artifact}.cert'
    args:
      - sign-blob
      - '--output-certificate=${certificate}' 
      - '--output-signature=${signature}'
      - '${artifact}'
      - --yes
    artifacts: all
    output: true

archives:
  - id: "kubearmor"
    builds:
      - "kubearmor"
    name_template: "{{.ProjectName}}_{{.Version}}_{{.Os}}-{{.Arch}}"
    files:
      - src: ./BPF/*
        dst: /opt/kubearmor/BPF/
      - src: ./templates/*
        dst: /opt/kubearmor/templates/
      - src: ./packaging/kubearmor.yaml
        dst: /opt/kubearmor/
        strip_parent: true
      - src: ./packaging/kubearmor.service
        dst: /usr/lib/systemd/system/
        strip_parent: true

nfpms:
  - id: "kubearmor"
    builds:
      - "kubearmor"
    formats:
      - deb
      - rpm
    replaces:
      - kubearmor
    maintainer: "Barun Acharya <barun.acharya@accuknox.com>"
    description: |
      Cloud-native Runtime Security Enforcement System
    vendor: "kubearmor"
    homepage: "https://kubearmor.com"
    license: "Apache 2"
    file_name_template: "{{.ProjectName}}_{{.Version}}_{{.Os}}-{{.Arch}}"
    bindir: /
    contents:
      - dst: /opt/kubearmor
        type: dir
      - src: ./BPF/*
        dst: /opt/kubearmor/BPF
      - src: ./templates/*
        dst: /opt/kubearmor/templates/
      - src: ./packaging/kubearmor.yaml
        dst: /opt/kubearmor/kubearmor.yaml
        type: config
      - src: ./packaging/kubearmor.service
        dst: /usr/lib/systemd/system/kubearmor.service
        type: config
      - src: /opt/kubearmor/kubearmor
        dst: /usr/local/bin/kubearmor
        type: symlink
    scripts:
      postinstall: packaging/post-install.sh
    overrides:
      deb:
        recommends:
          - make
          - libelf-dev
          - clang
          - llvm
          - linux-headers-generic
      rpm:
        recommends:
          - make
          - elfutils-libelf-devel
          - clang
          - llvm
          - kernel-devel
          - policycoreutils-devel
          - setools-console
