project_name: kubearmor

builds:
  - binary: "opt/kubearmor/kubearmor"
    id: kubearmor
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      
archives:
  - id: "kubearmor"
    builds:
      - "kubearmor"
    name_template: "{{.ProjectName}}_{{.Version}}_{{.Os}}-{{.Arch}}"
    files:
      - src: ./packaging/kubearmor.yaml
        dst: /opt/kubearmor
        strip_parent: true
      - src: ./packaging/kubearmor.service
        dst: /usr/lib/systemd/system
        strip_parent: true
      - src: ./karmor
        dst: /usr/local/bin
      - src: ./BPF/*
        dst: /opt/kubearmor/
      - src: ./templates/*
        dst: /opt/kubearmor/

nfpms:
  - id: "kubearmor"
    builds:
      - "kubearmor"
    formats:
      - deb
      - rpm
    replaces:
      - kubearmor
    maintainer: "Barun Acharya <barun.acharya@accuknox.com>"
    description: |
      Cloud-native Runtime Security Enforcement System
    vendor: "kubearmor"
    homepage: "https://kubearmor.com"
    license: "Apache 2"
    file_name_template: "{{.ProjectName}}_{{.Version}}_{{.Os}}-{{.Arch}}"
    bindir: /
    contents:
      - dst: /opt/kubearmor
        type: dir
      - src: ./BPF/*
        dst: /opt/kubearmor/BPF/
      - src: ./templates/*
        dst: /opt/kubearmor/templates/
      - src: ./packaging/kubearmor.yaml
        dst: /opt/kubearmor/kubearmor.yaml
        type: config
      - src: ./packaging/kubearmor.service
        dst: /usr/lib/systemd/system/kubearmor.service
        type: config
      - src: /opt/kubearmor/kubearmor
        dst: /usr/local/bin/kubearmor
        type: symlink
      - src: ./karmor
        dst: /usr/local/bin/karmor
    scripts:
      postinstall: packaging/post-install.sh
    overrides:
      deb:
        dependencies:
          - make
          - libelf-dev
          - clang
          - llvm
          - linux-headers-generic
      rpm:
        dependencies:
          - make
          - elfutils-libelf-devel
          - clang
          - llvm
          - kernel-devel
          - policycoreutils-devel
          - setools-console
