project_name: kubearmor

builds:
  - binary: kubearmor
    id: kubearmor
    goos:
      - linux
    goarch:
      - amd64

nfpms:
  - id: "kubearmor"
    builds:
      - "kubearmor"
    formats:
      - deb
      - rpm
    replaces:
      - kubearmor
    maintainer: "Barun Acharya <barun.acharya@accuknox.com>"
    description: |
      Cloud-native Runtime Security Enforcement System
    vendor: "kubearmor"
    homepage: "https://kubearmor.com"
    license: "Apache 2"
    file_name_template: "{{.ProjectName}}_{{.Version}}_{{.Os}}-{{.Arch}}"
    contents:
      - dst: /opt/kubearmor
        type: dir
      - src: ./packaging/kubearmor.conf
        dst: /opt/kubearmor/kubearmor.conf
        type: config
      - src: ./packaging/kubearmor.service
        dst: /usr/lib/systemd/system/kubearmor.service
        type: config
      - src: ./BPF/*
        dst: /opt/kubearmor/BPF/
      - src: ./templates/*
        dst: /opt/kubearmor/templates/
    scripts:
      postinstall: packaging/postinstall.sh
