// SPDX-License-Identifier: Apache-2.0
// Copyright 2021 Authors of KubeArmor

package filelessexec

import (
	"bytes"
	"encoding/binary"
	"errors"
	"log"
	"os"
	"strings"
	"sync"

	"github.com/cilium/ebpf"
	"github.com/cilium/ebpf/link"
	"github.com/cilium/ebpf/ringbuf"
	"github.com/cilium/ebpf/rlimit"
	"github.com/kubearmor/KubeArmor/KubeArmor/presets/base"

	fd "github.com/kubearmor/KubeArmor/KubeArmor/feeder"
	mon "github.com/kubearmor/KubeArmor/KubeArmor/monitor"
	tp "github.com/kubearmor/KubeArmor/KubeArmor/types"
)

//go:generate go run github.com/cilium/ebpf/cmd/bpf2go -cc clang filelessexec  ../../BPF/filelessexec.bpf.c -type event -no-global-types -- -I/usr/include/ -O2 -g

const (
	NAME   string = "FilelessExecutionPreset"
	EXISTS uint32 = 1024
)

type NsKey struct {
	PidNS uint32
	MntNS uint32
}

type ContainerVal struct {
	NsKey  NsKey
	Policy string
}

type FilelessExecPreset struct {
	base.BasePreset

	BPFContainerMap *ebpf.Map

	// events
	Events        *ringbuf.Reader
	EventsChannel chan []byte

	// ContainerID -> NsKey
	ContainerMap     map[string]ContainerVal
	ContainerMapLock *sync.RWMutex

	Link link.Link

	obj filelessexecObjects
}

type MmapEvent struct {
	Ts uint64

	PidID uint32
	MntID uint32

	HostPPID uint32
	HostPID  uint32

	PPID uint32
	PID  uint32
	UID  uint32

	EventID int32

	Retval int64

	Comm [80]byte

	Args [6]uint64
}

func NewFilelessExecPreset() *FilelessExecPreset {
	p := &FilelessExecPreset{}
	p.ContainerMap = make(map[string]ContainerVal)
	p.ContainerMapLock = new(sync.RWMutex)
	return p
}

func (p *FilelessExecPreset) Name() string {
	return NAME
}

func (p *FilelessExecPreset) RegisterPreset(logger *fd.Feeder, monitor *mon.SystemMonitor) (base.BasePresetInterface, error) {

	if logger.Enforcer != "BPFLSM" {
		// it's based on actibe enforcer, it might possible that node support bpflsm but
		// current enforcer is not bpflsm
		return nil, errors.New("FilelessExecutionPreset not supported if bpflsm not supported")
	}

	p.Logger = logger
	p.Monitor = monitor
	var err error

	if err = rlimit.RemoveMemlock(); err != nil {
		p.Logger.Errf("Error removing rlimit %v", err)
		return nil, err // Doesn't require clean up so not returning err
	}

	p.Logger.Printf("Preset Pinpath: %s\n", monitor.PinPath)

	p.BPFContainerMap, _ = ebpf.NewMapWithOptions(&ebpf.MapSpec{
		Type:       ebpf.Hash,
		KeySize:    8,
		ValueSize:  4,
		MaxEntries: 256,
		Pinning:    ebpf.PinByName,
		Name:       "fileless_exec_preset_containers",
	}, ebpf.MapOptions{
		PinPath: monitor.PinPath,
	})

	if err := loadFilelessexecObjects(&p.obj, &ebpf.CollectionOptions{
		Maps: ebpf.MapOptions{
			PinPath: monitor.PinPath,
		},
	}); err != nil {
		p.Logger.Errf("error loading BPF LSM objects: %v", err)
		return nil, err
	}

	p.Link, err = link.AttachLSM(link.LSMOptions{Program: p.obj.EnforceMmapFile})
	if err != nil {
		p.Logger.Errf("opening lsm %s: %s", p.obj.EnforceMmapFile.String(), err)
		return nil, err
	}

	p.Events, err = ringbuf.NewReader(p.obj.Events)
	if err != nil {
		p.Logger.Errf("opening ringbuf reader: %s", err)
		return nil, err
	}
	p.EventsChannel = make(chan []byte, mon.SyscallChannelSize)

	go p.TraceEvents()

	return p, nil

}

// TraceEvents traces events generated by bpflsm enforcer
func (p *FilelessExecPreset) TraceEvents() {

	if p.Events == nil {
		p.Logger.Err("ringbuf reader is nil, exiting trace events")
	}
	p.Logger.Print("Starting TraceEvents from FilelessProcessExec Presets")
	go func() {
		for {

			record, err := p.Events.Read()
			if err != nil {
				if errors.Is(err, ringbuf.ErrClosed) {
					// This should only happen when we call DestroyMonitor while terminating the process.
					// Adding a Warn just in case it happens at runtime, to help debug
					p.Logger.Warnf("Ring Buffer closed, exiting TraceEvents %s", err.Error())
					return
				}
				p.Logger.Warnf("Ringbuf error reading %s", err.Error())
				continue
			}

			p.EventsChannel <- record.RawSample

		}
	}()

	for {

		dataRaw := <-p.EventsChannel

		var event MmapEvent

		if err := binary.Read(bytes.NewBuffer(dataRaw), binary.LittleEndian, &event); err != nil {
			log.Printf("parsing ringbuf event: %s", err)
			continue
		}

		readLink := true
		// if len(string(bytes.Trim(event.Data.Source[:], "\x00"))) == 0 {
		// 	readLink = true
		// }

		containerID := ""

		if event.PidID != 0 && event.MntID != 0 {
			containerID = p.Monitor.LookupContainerID(event.PidID, event.MntID)
		}

		log := p.Monitor.BuildLogBase(event.EventID, mon.ContextCombined{
			ContainerID: containerID,
			ContextSys: mon.SyscallContext{
				PID:  event.PID,
				PPID: event.PPID,
				UID:  event.UID,

				HostPID:  event.HostPID,
				HostPPID: event.HostPPID,
			},
		}, readLink)

		// log.ClusterName = p.Logger.Node.ClusterName
		// log.HostName = p.Logger.Node.NodeName

		if ckv, ok := p.ContainerMap[containerID]; ok {
			log.PolicyName = ckv.Policy
			log.Type = "MatchedPolicy"
		}

		var f []string
		f = append(f, ParseProtectionFlags(event.Args[0]))
		f = append(f, ParseProtectionFlags(event.Args[1]))
		f = append(f, ParseMemoryFlags(event.Args[2]))
		if len(f) > 0 {
			log.Data = strings.Join(f, ",")
		}
		log.Operation = "File"
		if event.Retval >= 0 {
			log.Result = "Passed"
		} else {
			log.Result = "Permission denied"
		}
		log.Enforcer = base.PRESET_ENFORCER + NAME
		p.Logger.PushLog(log)

		p.Logger.Printf("FilelessProcessExec Alert: \n%+v\n", log)
		// dataRaw := <-p.EventsChannel

		// var event eventBPF

		// if err := binary.Read(bytes.NewBuffer(dataRaw), binary.LittleEndian, &event); err != nil {
		// 	log.Printf("parsing ringbuf event: %s", err)
		// 	continue
		// }

		// containerID := ""

		// if event.PidNS != 0 && event.MntNS != 0 {
		// 	containerID = p.Monitor.LookupContainerID(event.PidNS, event.MntNS)
		// }

		// if containerID != "" {
		// 	p.Logger.Printf("Alert event from cid %s for protect env preset with deets %+v", containerID, event)
		// }

	}
}

func (p *FilelessExecPreset) RegisterContainer(containerID string, pidns, mntns uint32) {
	ckv := NsKey{PidNS: pidns, MntNS: mntns}

	p.ContainerMapLock.Lock()
	defer p.ContainerMapLock.Unlock()
	p.Logger.Printf("[FilelessProcessExec] Registered container with id: %s\n", containerID)
	p.ContainerMap[containerID] = ContainerVal{NsKey: ckv}
}

func (p *FilelessExecPreset) UnregisterContainer(containerID string) {
	p.ContainerMapLock.Lock()
	defer p.ContainerMapLock.Unlock()

	if val, ok := p.ContainerMap[containerID]; ok {
		if err := p.DeleteContainerIDFromMap(containerID, val.NsKey); err != nil {
			p.Logger.Errf("error deleting container %s: %s", containerID, err.Error())
			return
		}
		p.Logger.Printf("[FilelessProcessExec] Unregistered container with id: %s\n", containerID)
		delete(p.ContainerMap, containerID)
	}
}

func (p *FilelessExecPreset) AddContainerIDToMap(id string, ckv NsKey) error {
	p.Logger.Printf("[FilelessProcessExec] adding container with id to fileless exec map: %s\n", id)
	if err := p.BPFContainerMap.Put(ckv, EXISTS); err != nil {
		p.Logger.Errf("error adding container %s to outer map: %s", id, err)
		return err
	}
	return nil
}

func (p *FilelessExecPreset) DeleteContainerIDFromMap(id string, ckv NsKey) error {
	p.Logger.Printf("[FilelessProcessExec] deleting container with id to fileless exec map: %s\n", id)
	if err := p.BPFContainerMap.Delete(ckv); err != nil {
		if !errors.Is(err, os.ErrNotExist) {
			p.Logger.Errf("error deleting container %s in fileless_exec_preset_containers map: %s", id, err.Error())
			return err
		}
	}
	return nil
}

func (p *FilelessExecPreset) UpdateSecurityPolicies(endPoint tp.EndPoint) {
	var fileExecPresetRulePresent bool
	for _, cid := range endPoint.Containers {
		fileExecPresetRulePresent = false
		p.Logger.Printf("Updating container preset rules for %s", cid)
		for _, secPolicy := range endPoint.SecurityPolicies {
			for _, preset := range secPolicy.Spec.Presets {
				if preset == tp.FilelessProcessExec {
					fileExecPresetRulePresent = true
					p.ContainerMapLock.RLock()
					// Check if Container ID is registered in Map or not
					ckv, ok := p.ContainerMap[cid]
					if !ok {
						// It maybe possible that CRI has unregistered the containers but K8s construct still has not sent this update while the policy was being applied,
						// so the need to check if the container is present in the map before we apply policy.
						p.ContainerMapLock.RUnlock()
						return
					}
					ckv.Policy = secPolicy.Metadata["policyName"]
					p.ContainerMap[cid] = ckv
					err := p.AddContainerIDToMap(cid, ckv.NsKey)
					if err != nil {
						p.Logger.Warnf("updating policy for container %s :%s ", cid, err)
					}
					p.ContainerMapLock.RUnlock()
				}
			}
		}
		if !fileExecPresetRulePresent {
			p.ContainerMapLock.RLock()
			ckv := p.ContainerMap[cid]
			_ = p.DeleteContainerIDFromMap(cid, ckv.NsKey)
			p.ContainerMapLock.RUnlock()
		}
	}
}

func (p *FilelessExecPreset) Destroy() error {
	if p == nil {
		return nil
	}
	var errBPFCleanUp error

	if err := p.obj.Close(); err != nil {
		p.Logger.Err(err.Error())
		errBPFCleanUp = errors.Join(errBPFCleanUp, err)
	}

	if err := p.Link.Close(); err != nil {
		p.Logger.Err(err.Error())
		errBPFCleanUp = errors.Join(errBPFCleanUp, err)
	}

	p.ContainerMapLock.Lock()

	if p.BPFContainerMap != nil {
		if err := p.BPFContainerMap.Unpin(); err != nil {
			p.Logger.Err(err.Error())
			errBPFCleanUp = errors.Join(errBPFCleanUp, err)
		}
		if err := p.BPFContainerMap.Close(); err != nil {
			p.Logger.Err(err.Error())
			errBPFCleanUp = errors.Join(errBPFCleanUp, err)
		}
	}

	p.ContainerMapLock.Unlock()

	if p.Events != nil {
		if err := p.Events.Close(); err != nil {
			p.Logger.Err(err.Error())
			errBPFCleanUp = errors.Join(errBPFCleanUp, err)
		}
	}

	p = nil
	return errBPFCleanUp
}
