name: ci-build-and-push

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up QEMU for multi-architecture builds
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/amd64,linux/arm64/v8

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_AUTHTOK }}

      - name: Build and push multi-architecture image
        uses: docker/build-push-action@v6
        with:
            context: .
            file: examples/multiubuntu/build/Dockerfile  
            push: true
            tags: ${{ secrets.DOCKER_USERNAME }}/multiubuntu:latest
            platforms: linux/amd64,linux/arm64/v8 

      - name: Logout from Docker Hub
        run: docker logout
