name: ci-codespell

on:
  workflow_call:

permissions: read-all

jobs:
  codespell:
    name: Check misspelled words
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run codespell
        uses: codespell-project/actions-codespell@v2
        with:
          check_hidden: true
