name: ci-codespell

on:
  workflow_call:

permissions: read-all

jobs:
  codespell:
    name: Check misspelled words
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - name: Run codespell
        uses: codespell-project/actions-codespell@8f01853be192eb0f849a5c7d721450e7a467c579 # v2
        with:
          check_hidden: true
