name: ci-merge-coverage

on:
  workflow_run:
    workflows: [ci-test-ginkgo]
    types:
      - completed

permissions: read-all

jobs:
  merge-coverage-files:
    name: Download and merge files
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      actions: read
      contents: read
    steps:
      - name: Check if all required workflows completed successfully
        id: check-workflows
        run: |
          workflows=("ci-test-ginkgo")
          all_completed=true

          commit_sha=$(git rev-parse HEAD)

          for workflow in "${workflows[@]}"; do
              conclusion=$(gh run list --workflow=$workflow --json conclusion,headSha,event,headBranch | jq -r --arg sha "$commit_sha" --arg event "pull_request" '.[] | select(.headSha == $sha and .event == $event) | .conclusion')

              if [[ -z "$conclusion" ]]; then
                  conclusion="pending"
              fi

              if [[ "$conclusion" != "success" ]]; then
                  all_completed=false
              fi

              echo "${workflow}_status=$conclusion" >> $GITHUB_ENV
          done

          if [[ "$all_completed" == "true" ]]; then
              echo "All workflows completed successfully for commit $commit_sha."
              echo "all_succeeded=true" >> $GITHUB_ENV
          else
              echo "Not all workflows completed successfully for commit $commit_sha."
              exit 1
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          submodules: true

      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version-file: "KubeArmor/go.mod"

      - name: Download k8s coverage files from ci-test-ginkgo
        if: ${{ env.ci-test-ginkgo_status == 'success' }}
        uses: dawidd6/action-download-artifact@20319c5641d495c8a52e688b7dc5fada6c3a9fbc # v8
        with:
          workflow: ci-test-ginkgo.yml
          name: coverage.*
          path: KubeArmor/
          name_is_regexp: true
          search_artifacts: true

      - uses: codecov/codecov-action@13ce06bfc6bbe3ecf90edbbf1bc32fe5978ca1d3 # v5.3.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
