name: ci-test-operator

on:
  workflow_call:

# Declare default permissions as read only.
permissions: read-all

jobs:
  kubearmor-operator-test:
    name: Build KubeArmor Operator
    defaults:
      run:
        working-directory: ./pkg/KubeArmorOperator
    runs-on: ubuntu-22.04
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5
        with:
          # working-directory only takes effect for "run"
          go-version-file: 'KubeArmor/go.mod'

      - name: Build kubearmor operator
        run: make docker-build TAG=latest
