name: ci-test-go

on:
  workflow_call:
# Declare default permissions as read only.
permissions: read-all

jobs:
  go-fmt:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5
        with:
          go-version-file: "KubeArmor/go.mod"

      - name: Check gofmt
        run: make gofmt
        working-directory: KubeArmor

  go-lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5
        with:
          go-version-file: "KubeArmor/go.mod"

      - name: Run Revive Action on KubeArmor
        uses: morphy2k/revive-action@7b25e715309495d5c3cdef7caccb65ad9fa74ba3 # v2
        with:
          path: "./KubeArmor/..."

  go-lint-tests:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5
        with:
          go-version-file: "KubeArmor/go.mod"

      - name: Run Revive Action on KubeArmor tests
        uses: morphy2k/revive-action@7b25e715309495d5c3cdef7caccb65ad9fa74ba3 # v2
        with:
          path: "./tests/..."

  go-sec:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5
        with:
          go-version-file: "KubeArmor/go.mod"

      - name: Install LLVM/Clang
        run: ./.github/workflows/install-llvm.sh

      - name: Install libbpf headers
        run: sudo apt-get update && sudo apt-get install -y libbpf-dev

      # Install BPF tool
      - name: Install bpftool
        run: ./.github/workflows/install-bpftool.sh

      - name: Generate vmlinux.h
        run: make -C BPF kernel_headers
        working-directory: KubeArmor

      - name: Generate BPF files
        run: go generate ./...
        working-directory: KubeArmor

      - name: Run Gosec Security Scanner
        run: make gosec
        working-directory: KubeArmor

  go-vuln:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5
        with:
          go-version-file: "KubeArmor/go.mod"

      - name: Install LLVM/Clang
        run: ./.github/workflows/install-llvm.sh

      - name: Install libbpf headers
        run: sudo apt-get update && sudo apt-get install -y libbpf-dev

      - name: Install bpftool
        run: ./.github/workflows/install-bpftool.sh

      - name: Generate vmlinux.h
        run: make -C BPF kernel_headers
        working-directory: KubeArmor

      - name: Generate BPF files
        run: go generate ./...
        working-directory: KubeArmor

      - name: Run govulncheck
        run: make scan
        working-directory: KubeArmor

  go-test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5
        with:
          go-version-file: "KubeArmor/go.mod"

      - name: Install LLVM/Clang
        run: ./.github/workflows/install-llvm.sh

      - name: Install libbpf headers
        run: sudo apt-get update && sudo apt-get install -y libbpf-dev

      - name: Install bpftool
        run: ./.github/workflows/install-bpftool.sh

      - name: Generate vmlinux.h
        run: make -C BPF kernel_headers
        working-directory: KubeArmor

      - name: Generate BPF files
        run: go generate ./...
        working-directory: KubeArmor

      - name: Run go test on the KubeArmor/KubeArmor directory
        run: go test -coverprofile=coverage.txt -covermode=atomic ./...
        working-directory: KubeArmor

      - name: Upload code coverage to Codecov
        uses: codecov/codecov-action@b9fd7d16f6d7d1b5d2bec1a2887e65ceed900238 # v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: KubeArmor/coverage.txt
          flags: unittests
          fail_ci_if_error: false

  license:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Install LLVM/Clang
        run: ./.github/workflows/install-llvm.sh

      - name: Install libbpf headers
        run: sudo apt-get update && sudo apt-get install -y libbpf-dev

      - name: Install bpftool
        run: ./.github/workflows/install-bpftool.sh

      - name: Generate vmlinux.h
        run: make -C BPF kernel_headers
        working-directory: KubeArmor

      - name: Generate BPF files
        run: go generate ./...
        working-directory: KubeArmor

      - name: Run go test on the KubeArmor/KubeArmor directory
        run: go test ./...
        working-directory: KubeArmor
