name: ci-test-helm-charts

on:
  push:
    branches: [main]
    paths:
      - "deployments/helm/**"
      - ".github/workflows/ci-test-helm-charts.yml"
  pull_request:
    branches: [main]
    paths:
      - "deployments/helm/**"
      - ".github/workflows/ci-test-helm-charts.yml"

# Declare default permissions as read only.
permissions: read-all

jobs:
  lint:
    name: Helm Chart Tests / < matrix variable >
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: actions/setup-go@v3
        with:
          go-version: "v1.20"

      - uses: azure/setup-helm@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: helm lint
        run: |
          helm lint ./deployments/helm/KubeArmor
          helm lint ./deployments/helm/KubeArmorOperator

      - name: Validate helm environment template values
        run: |
          ./.github/workflows/helm-validate-values.sh
