name: osv-scan

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "0 6 * * 1"
  workflow_dispatch: {}

permissions: read-all

jobs:
  osv-scan-pr:
    if: ${{ github.event_name == 'pull_request' }}
    permissions:
      contents: read
      security-events: write
      actions: read
    uses: "google/osv-scanner-action/.github/workflows/osv-scanner-reusable-pr.yml@8deb546fdb875b9996d27d4950be7312dac076a1" # v2.5.0
    with:
      scan-args: |-
        --recursive
        .
      fail-on-vuln: true

  osv-scan-full:
    if: ${{ github.event_name == 'pull_request' }}
    permissions:
      contents: read
      security-events: write
      actions: read
    uses: "google/osv-scanner-action/.github/workflows/osv-scanner-reusable.yml@8deb546fdb875b9996d27d4950be7312dac076a1" # v2.5.0
    with:
      scan-args: |-
        --recursive
        .
      fail-on-vuln: true

  osv-scan:
    if: ${{ github.event_name != 'pull_request' }}
    permissions:
      contents: read
      security-events: write
      actions: read
    uses: "google/osv-scanner-action/.github/workflows/osv-scanner-reusable.yml@8deb546fdb875b9996d27d4950be7312dac076a1" # v2.5.0
    with:
      scan-args: |-
        --recursive
        .
      fail-on-vuln: true
