name: osv-scan

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "0 6 * * 1"
  workflow_dispatch: {}

permissions: read-all

jobs:
  osv-scan-pr:
    if: ${{ github.event_name == 'pull_request' }}
    permissions:
      contents: read
      security-events: write
      actions: read
    uses: "google/osv-scanner-action/.github/workflows/osv-scanner-reusable-pr.yml@9a498708959aeaef5ef730655706c5a1df1edbc2" # v2.3.8
    with:
      scan-args: |-
        --recursive
        .

  osv-scan:
    if: ${{ github.event_name != 'pull_request' }}
    permissions:
      contents: read
      security-events: write
      actions: read
    uses: "google/osv-scanner-action/.github/workflows/osv-scanner-reusable.yml@9a498708959aeaef5ef730655706c5a1df1edbc2" # v2.3.8
    with:
      scan-args: |-
        --recursive
        .
