name: Renovate

on:
  schedule:
    - cron: "0 3 * * 1"
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level (debug, info, warn, error)"
        required: false
        default: "info"
        type: string

permissions: {}
concurrency:
  group: renovate
  cancel-in-progress: false

jobs:
  renovate:
    name: Renovate
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write
      issues: write

    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@79dc0ba74dc3de28db0a7aeb1d0b95d5bf5fde2a # v46.1.13
        env:
          LOG_LEVEL: ${{ github.event.inputs.logLevel || 'info' }}
          RENOVATE_GIT_AUTHOR: "Renovate Bot <29139614+renovate[bot]@users.noreply.github.com>"
          RENOVATE_REPOSITORIES: ${{ github.repository }}
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
