name: Renovate

on:
  schedule:
    - cron: "0 3 * * 1"
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level (debug, info, warn, error)"
        required: false
        default: "info"
        type: string

concurrency:
  group: renovate
  cancel-in-progress: false

jobs:
  renovate:
    name: Renovate
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write
      issues: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v46.1.13
        env:
          LOG_LEVEL: ${{ inputs.logLevel || 'info' }}
          RENOVATE_GIT_AUTHOR: "Renovate Bot <29139614+renovate[bot]@users.noreply.github.com>"
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
          repository: Athang69/KubeArmor