name: Generate SBOM
on:
  workflow_dispatch:
  release:
    types: [published]
permissions:
  contents: write
jobs:
  generate_sbom_action:
    runs-on: ubuntu-latest
    name: Install K8s bom and generate SBOM
    steps:
      - name: Checkout repository
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f

      - name: Install bom
        uses: kubernetes-sigs/release-actions/setup-bom@841d76a188a7c121231a863572e27012805715a2

      - name: Generage SBOM
        run: |
          bom generate --format json --analyze-images --output kubearmor_${{github.ref_name}}_sbom.spdx.json \
          --dirs=.\

      - name: Upload SBOM
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{github.ref_name}} kubearmor_${{github.ref_name}}_sbom.spdx.json
