apiVersion: security.kubearmor.com/v1
kind: KubeArmorHostPolicy
metadata:
  name: hsp-kubearmor-dev-file-dir-block-fromsource
spec:
  nodeSelector:
    matchLabels:
      kubernetes.io/hostname: kubearmor-dev
  severity: 5
  file:
    matchDirectories:
    - dir: /home/vagrant/selinux-test/matchDir/
      fromSource:
      - path: /home/vagrant/selinux-test/read
  action:
    Block

# test
# (/home/vagrant/selinux-test/) $ cat matchDir/test1 (test2 test3 test4 test5)
# test1
# (/home/vagrant/selinux-test/) $ ./read matchDir/test1 (test2 test3 test4 test5)
# failed to open test1 with the READONLY mode

# expectation
# anyone can access /home/vagrant/selinux-test/matchDir/*
# /home/vagrant/selinux-test/read cannot access /home/vagrant/selinux-test/matchDir/*
