apiVersion: security.kubearmor.com/v1
kind: KubeArmorHostPolicy
metadata:
  name: hsp-kubearmor-dev-proc-path-block-fromsource
spec:
  nodeSelector:
    matchLabels:
      kubernetes.io/hostname: kubearmor-dev
  severity: 5
  process:
    matchPaths:
    - path: /home/vagrant/selinux-test/write
      fromSource:
      - path: /home/vagrant/selinux-test/bash
  action:
    Block

# test
# (/home/vagrant/selinux-test/) $ ./write
# Usage: ./write [file]
# (/home/vagrant/selinux-test/) $ ./bash -c ./write
# ./bash: ./write: Permission denied

# expectation
# anyone can execute /home/vagrant/selinux-test/write
# /home/vagrant/selinux-test/bash cannot execute /home/vagrant/selinux-test/write
