apiVersion: security.kubearmor.com/v1
kind: KubeArmorHostPolicy
metadata:
  name: hsp-kubearmor-dev-file-path-allow-fromsource
spec:
  nodeSelector:
    matchLabels:
      kubernetes.io/hostname: kubearmor-dev
  severity: 5
  file:
    matchPaths:
    - path: /home/vagrant/selinux-test/file.txt
      fromSource:
      - path: /home/vagrant/selinux-test/read
  action:
    Allow

# test
# (/home/vagrant/selinux-test/) $ cat file.txt
# cat: file.txt: Permission denied
# (/home/vagrant/selinux-test/) $ ./read file.txt
# read hello from file.txt

# expectation
# anyone cannot access /home/vagrant/selinux-test/file.txt
# /home/vagrant/selinux-test/read can access /home/vagrant/selinux-test/file.txt
