apiVersion: security.kubearmor.com/v1
kind: KubeArmorHostPolicy
metadata:
  name: hsp-kubearmor-dev-file-dir-allow-fromsource
spec:
  nodeSelector:
    matchLabels:
      kubernetes.io/hostname: kubearmor-dev
  severity: 5
  file:
    matchDirectories:
    - dir: /home/vagrant/selinux-test/matchDir/
      fromSource:
      - path: /home/vagrant/selinux-test/read
  action:
    Allow

# test
# (/home/vagrant/selinux-test/) $ cat matchDir/test1 (test2 test3 test4 test5)
# cat: test1: Permission denied
# (/home/vagrant/selinux-test/) $ ./read matchDir/test1 (test2 test3 test4 test5)
# read test1
#  from matchDir/test1

# expectation
# anyone cannot access /home/vagrant/selinux-test/matchDir/*
# /home/vagrant/selinux-test/read can access /home/vagrant/selinux-test/matchDir/*
